### ISSUE TITLE
can't add in to .net framework 4.0 project

### ISSUE THREAD

**Issue by SealinRepo** [bezzad/Downloader#1]
Hi:
 I have a project using .net 4.0, and extended the "async await" keyword, but install this dependency failed, can I use it in my project?
 best wish.

**Comment by bezzad** [comment]
Hi, @SealinRepo 

This repository is written in `.NetStandard2.0` and according to the [following link](0), can't support the `.Net40`. And the minimum version of `.NetFramework` can be supported by this project is `.Net4.6.1`.

[0]: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I try to downgrade the .net version but `.Net40` no many dependencies of this project.

Thanks
bezzad
