### ISSUE TITLE
Missing Interface, Events/EventArgs issue

### ISSUE THREAD

**Issue by Borningstar** [bezzad/Downloader#10]
I'd like to have an interface for `DownloadService `so I can mock it to facilitate testing.

There's also a couple issues with the events that means I can't convert them to Observables: 

`DownloadProgressChangedEventArgs `should be a child of `EventArgs`, the `EventHandler`s should all be declared with `event`.

I've resolved these myself, all test passing, however I'm unable to push the branch to be reviewed. Could you please change the repo permissions to allow contributors to put up stuff?

**Comment by bezzad** [comment]
Hi, 
Yes, all right. I try to fix that in the next version as soon. You can fork and change this project and so send a pull request.
I promise to you, I merge that to the master branch as soon as possible.

**Comment by bezzad** [comment]
@Borningstar I added you as a collaborator of this project. Feel free to change or add a new feature.

**Comment by bezzad** [comment]
@Borningstar I updated and released the new version 1.4.0. Please check if all of your requirements have been met.

**Comment by Borningstar** [comment]
@bezzad Thanks, looks like it's exactly what I need and thanks for the collab add
