### ISSUE TITLE
Question about download operation

### ISSUE THREAD

**Issue by ZCOREP** [bezzad/Downloader#105]
If we download with 3 chunks and we want to get the total download percentage (in one place), how should we get it?

**Comment by bezzad** [comment]
Please read [this section](https://github.com/bezzad/Downloader#step-3-handle-download-events) of the readme.
The downloader has two events to get momentary progress info. One is for per chunk and another is for total progress of a download.

So, you can use the `DownloadProgressChanged` event to handle total progress bytes and percentages like the below sample:

```csharp
downloadService.DownloadProgressChanged += OnDownloadProgressChanged;

private static void OnDownloadProgressChanged(object sender, DownloadProgressChangedEventArgs e)
{
            var totalDownloadPercent = e.ProgressPercentage * 100;
}
```
