### ISSUE TITLE
await downloader.DownloadFileTaskAsync(url, path); RETURN FILNAME

### ISSUE THREAD

**Issue by david127cu** [bezzad/Downloader#106]
Imagine this scenario. I am using your library to download files on VPS. After downloading the file I need to continue manipulating it with my application, but I don't have the name, only the address of the folder where it is stored. Assuming that I want to move the file to another location with my application it would be somewhat problematic if there are several files in that folder...

await downloader.DownloadFileTaskAsync(url, path); could return the full output address or the file name?

I took the code from README.md Step 4b

**Comment by bezzad** [comment]
You can use the `Package` object to get all info about a download, like:  `downloader.Package.FileName`

**Comment by david127cu** [comment]
I spoke to him on telegram.

**Comment by bezzad** [comment]
Please give me your download URL to check what the problem is.
All of your methods have been implemented on our downloader.

**Comment by bezzad** [comment]
Example link: https://rs17.seedr.cc/get_zip_ngen_free/149605004/Thor.Love.and.Thunder.2022.720p.WEBRip.800MB.x264-GalaxyRG[TGx].zip?st=XGSqYEtPiKmJcU-2PNNxjg&e=1663157407

**Comment by david127cu** [comment]
great
