### ISSUE TITLE
[Feature Request] Progress notifications for chunk copying

### ISSUE THREAD

**Issue by CarbonNeuron** [bezzad/Downloader#109]
I saw in #54 that it is difficult to write the file directly to the final location. So, something that would make this more friendly is to be able to get notified of the progress of the copy to the final directory.
A scenario when this would be useful:
You have a UI that downloads a large file, 8GB for example. We have progress notifications for the download so the user can see the file downloading, But once it reaches 100%, the program just sits and waits until it is done copying to the final location. Which could be a few minutes on a slow drive.
 
My proposal is that instead of it sitting and waiting, We should receive progress notifications for the final copy. That way the user knows that something is still happening and the UI is not frozen.

**Comment by bezzad** [comment]
This issue will be solved as soon as possible by `Memory Mapped Files`. In the new version `2.5.0` we can download the stream as parallel on the final file. 
Thanks a lot for your Pull requests.

**Comment by CarbonNeuron** [comment]
> This issue will be solved as soon as possible by [MemoryMappedFiles](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=netstandard-2.0). In the new version `2.5.0` we can download the stream as parallel on the final file. Thanks a lot for your Pull requests.

Alright cool. Thanks for this great downloading library.

**Comment by bezzad** [comment]
@CarbonNeuron new version release and you can see the new feature on this version, now.
If the feature you requested was completed in this version, please let us know so that the final version can be published.
The changes in this version are fundamental and that is why this version is beta.

**Comment by bezzad** [comment]
I close this issue because this feature was added in the last version. if you have a problem with that, please create a new issue.
