### ISSUE TITLE
Corrupted download

### ISSUE THREAD

**Issue by WellitonToledo** [bezzad/Downloader#115]
Hello,

trying to download a zip file from an `.ashx handler` url.

Most of the times the downloaded file is corrupted.

Here the code:

```
using Downloader;

var downloadOpt = new DownloadConfiguration()
{
    ChunkCount = 1, // file parts to download, default value is 1
    OnTheFlyDownload = true, // caching in-memory or not? default values is true
    ParallelDownload = false // download parts of file as parallel or not. Default value is false
};

var downloader = new DownloadService(downloadOpt);

string file = @"YourPath\fileName.zip";
string url = @"https://vl.actuar.net.br/ActuarAcesso";

downloader.DownloadFileTaskAsync(url, file).Wait();
```

Regards,

**Comment by bezzad** [comment]
@WellitonToledo Please use the last version of the Downloader (v3.0.0-beta) and if you have a problem again let me know. I tested it with the new version and it has no issues.

**Comment by bezzad** [comment]
@WellitonToledo Is your problem solved with the new version or not?

**Comment by bezzad** [comment]
version 3.0.1 was released too.
