### ISSUE TITLE
the download suddenly dispose

### ISSUE THREAD

**Issue by ZCOREP** [bezzad/Downloader#125]
Hello ,
I'm using your package for download in my application. i have a download list in my application. sometimes the download suddenly dispose.  
why?

**Comment by bezzad** [comment]
Hi @ZCOREP,
Which object is disposed of? The "DownloadService" object is never disposed unless you call the dispose method or use the "using" syntax to dispose of it after a scope.
Please share a sample application with me so that I can investigate this issue.
Thanks

**Comment by ZCOREP** [comment]
Hello, Sorry for late. i am using UWP Framework, and MVVM Toolkit.  the code is in zip file . its just ye sample
[SimpleDownload.zip](https://github.com/bezzad/Downloader/files/11132036/SimpleDownload.zip)

**Comment by ZCOREP** [comment]
did you see it?
