### ISSUE TITLE
Cannot serialize download package after cancelled or failed.

### ISSUE THREAD

**Issue by zaevi** [bezzad/Downloader#129]
Hi, I want to serialize download package when downloading is cancelled or failed, so that I can resume downloading next time. But when serializing it throws `ObjectDisposedException`:

```csharp
// .net7 top-level program
using Downloader;

var downloader = new DownloadService();

var times = 3;
downloader.ChunkDownloadProgressChanged += (_, e) =>
{
    if (times-- == 0) downloader.CancelAsync();
};

downloader.DownloadFileCompleted += (_, e) =>
{
    var package = e.UserState as DownloadPackage;
    if(package!.Status != DownloadStatus.Completed)
        JsonSerializer.Serialize(package!); // throws ObjectDisposedException
};

var url = "http://cachefly.cachefly.net/10mb.test";
await downloader.DownloadFileTaskAsync(url, "./download.test");
```

**Comment by bezzad** [comment]
Your code is not correct. We didn't set `e.UserState` as `DownloadPackage`. 
Please use it like this:

```csharp
var package = downloader.Package;
```

or

```csharp
var package = (sender as DownloadService).Package;
```

**Comment by zaevi** [comment]
> Please use it like this:
> 
> ```cs
> var package = downloader.Package;
> ```
> 
> or
> 
> ```cs
> var package = (sender as DownloadService).Package;
> ```
> 
> `sender` object is the same with `_` in your codes ;)

It's same reference and it still throws the exception. 
Seems `package.Storage` has been disposed so it can't be serialized.

**Comment by bezzad** [comment]
This issue was fixed with the test. Please test the Downloader new version 3.0.3. If you have the problem again, so re-open this issue.
Thank you for reporting and the pull request.
