### ISSUE TITLE
"The process cannot access the file 'D:\testdownload\100MB-london.bin' because it is being used by another process."

### ISSUE THREAD

**Issue by AlanWeekend** [bezzad/Downloader#132]
After closing the software, I use the software package to continue downloading. Normal for the first time, error for the second time, normal for the third time, and error for the fourth time. This cycle. I don't know what's wrong. Please help me

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218323079-b5027cc5-32a1-439d-aa21-1cadddeae0d5.png)
This is the code that I execute when I close the software

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218323167-9870b360-8244-4580-882b-8449cea002f7.png)
When I open the software again, I will read the package and resume the download

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218323205-26e87b5d-6af2-46cb-86ec-ef1f5913b611.png)

**Comment by bezzad** [comment]
If you want to stop the download or shutdown application, please use the `Stop` function instead of `Pause`.
When you use the `Pause` function, the Download just blocks the current download process and releases it when resuming. But, when you use the `Stop` function the download process is killed and closed the file streams to use another time.
Please check this way and feedback to me know what happened.

**Comment by bezzad** [comment]
So your code must be like the below codes:

```csharp
public void SaveDownloadPackages()
{
     if(downloadPackage != null)
     {
           foreach(var download in downloadItems)
           {
                 download.Service.Stop(); 
           }
           ...
     }
}
```

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218380538-4354bf0f-afc8-4798-b86b-ce79755e4eb9.png)

service has no ``stop`` function, i use 3.0.3 version

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218380829-4e296183-aaaf-4285-9807-b1b1d7dfa7a7.png)

these are all function in DownloadService

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218384161-3622b340-0571-421e-942a-e5f4b1be873e.png)

I use DownloadBuilder to create the download object and stop it at the end using the stop function. This is useless, it will still have the same mistakes

**Comment by bezzad** [comment]
Excuse me, I think you used the `DownloadBuilder` class. Please call the `CancelAsync` method which that name is `Stop` in Fluent models.

**Comment by bezzad** [comment]
Your meaning is this way still have the same issue with **Process cannot access ...** ?

**Comment by AlanWeekend** [comment]
yes

**Comment by bezzad** [comment]
To explain more and with actual details, I should ask about this issue's steps. Do you accept this way is the same with your scenario which has this issue?
* Start a download
* Stop the download 
* Store `DownloadPackage`
* Shutdown application
* Open application
* Resume the download with stored `DownloadPakcage`
* Still work correctly
* Repeat these steps again
* Throw `The process cannot access the file` exception

**Comment by AlanWeekend** [comment]
yes

**Comment by bezzad** [comment]
I will check this with the tests and come back as soon as possible.
Thanks for reporting the issue.

**Comment by AlanWeekend** [comment]
You're welcome. Thank you for your work

**Comment by AlanWeekend** [comment]
I created a new winform project to try to reproduce this problem. It works normally. But in my project (winform+webview2), this problem is inevitable. I am trying to create a winform+webview2 demo to reproduce this problem. If it happens, I will tell you at the first time

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/218412431-d4b3af55-feaa-4f04-9ef4-7a431f7d63a3.png)

![image](https://user-images.githubusercontent.com/24834613/218412399-65631ee5-e00f-4896-b78d-c8176ed8e538.png)

I think I found the reason. CancelAsync closed before it finished executing the program. I added a delay of 1 second, and the problem no longer occurs. Do you have a synchronous cancel function or a callback after execution

**Comment by bezzad** [comment]
The `CancelAsync` method is a synchronous state setter that fires a cancellation token and sets a state as the stop for the running tasks. But, the tasks have self organize and decide when close self-connections after seeing this state as `Stop`.
Now, I don't understand why don't close the tasks when your app closed immediately after changing the state to stop!

**Comment by bezzad** [comment]
Can you share a sample project with me that has this issue?

**Comment by AlanWeekend** [comment]
I tried to create a new project to reproduce this problem, but it works normally. I will consider how to desensitize the actual project and share it with you

**Comment by AlanWeekend** [comment]
I sent the sample project to your gmail

**Comment by bezzad** [comment]
Thanks a lot @AlanWeekend  
I will check it and feedback here as soon as possible.

**Comment by AlanWeekend** [comment]
> It seems it is because the `DownloadPackage.Storage` property is per default serialized into JSON (using System.Text.Json), and also deserialized:
> 
> ```json
> {
>   "Storage":{"Path":"C:\\dir\\file.txt"}
> }
> ```
> 
> ```cs
> JsonSerializer.Serialize(download.Package);
> JsonSerializer.Deserialize<DownloadPackage>(progressFile);
> ```
> 
> That causes the deserializer to create a `Stream` which holds a file lock on the partial file. When continuing with `await download.DownloadFileTaskAsync(downloadPackage, cancellationToken);`, the download fails with mentioned exception as it tries to create another stream.
> 
> Workaround: call `.Dispose()` on the deserialized download package storage stream before continuing download.
> 
> ```cs
> downloadPackage.Storage.Dispose();
> ```

tks, i will try it

**Comment by bezzad** [comment]
@AlanWeekend please use the new version 3.0.4. In the latest version, you can use the `CancelTaskAsync` method to wait to complete all tasks.

**Comment by AlanWeekend** [comment]
> @AlanWeekend请使用新版本 3.0.4。在最新版本中，您可以使用该方法等待完成所有任务。`CancelTaskAsync`

ok
