### ISSUE TITLE
Resume download with a different URL

### ISSUE THREAD

**Issue by UrbanCMC** [bezzad/Downloader#136]
I'm currently trying to integrate your library into a project I'm using, but some of the URLs that are used are generated through an API that gives them an expiration date.

Would it be possible to extend the `DownloadFileTaskAsync` method to accept a new URL in addition to the download package, or do you foresee any problems with this?

**Comment by hankb299** [comment]
Sure I will. What do I need to do exactly?

**Comment by bezzad** [comment]
This feature was added to the new version 3.0.6. Please check it and add a new issue if you find a problem.

How to use:

```csharp
var url =  "your_first_link_of_download_file";
var newUrl =  "your_first_link_of_download_file";

var downloader = new DownloadService(config);
await downloader.DownloadFileTaskAsync(url).ConfigureAwait(false);

// resume after canceling upper download
await downloader.DownloadFileTaskAsync(downloader.Package, newUrl); 
```
