### ISSUE TITLE
How to make the block file change to another directory。

### ISSUE THREAD

**Issue by Exception-King** [bezzad/Downloader#15]

**Comment by bezzad** [comment]
Hi @Exception-King 
This isn't of the Downloader library features, but if you want to that change it, so I can make that for you in the next version as soon as possible.

**Comment by bezzad** [comment]
Added TempDirectory properties into options to set chunk files storage path when the OnTheFlyDownload option is false.
Please check the new version 1.7.0 for this feature.

Thanks
