### ISSUE TITLE
The 67th Line in this file“Downloader/src/Downloader /ChunkDownloader.cs ” is not need

### ISSUE THREAD

**Issue by wybarcelona** [bezzad/Downloader#156]
The 67th Line in this file“Downloader/src/Downloader /ChunkDownloader.cs ” is not need;

if server is supported range download, when a file downloads fail,the  code of 67th line will throw a exception 

![11115](https://github.com/bezzad/Downloader/assets/66719951/99a683e0-00e7-4f3f-b60a-22492cde8ade)

**Comment by bezzad** [comment]
Consider a situation where the server does not allow resuming a download from a specific position. Now, something like an error occurs during the download and this method is entered to resume the download. Now the server can't resume the download, so the download should be stopped by throwing an error.
