### ISSUE TITLE
How to change the URL when resume

### ISSUE THREAD

**Issue by aiguoli** [bezzad/Downloader#164]
I use `Downloader` to download files from OneDrive in my project. The link is time sensitive. So when resuming the download, it is necessary to reset the download address. 

In theversion `3.0.6`, I change Adress with code like this:
```csharp
DownloadPackage _pack = _downloader.Package;
string downloadUrl = item.AdditionalData["@microsoft.graph.downloadUrl"].ToString();
_pack.Address = downloadUrl;
if (_pack != null)
{
    await _downloader.DownloadFileTaskAsync(_pack);
}
```
But with version of `3.1.2`, `Address` attribute seems to have been removed. So how can I dynamically change the file address?

**Comment by bezzad** [comment]
To reset the URL in the resuming package you can code like the below way:

```csharp
IDownload download = DownloadBuilder.New().WithUrl("https://new_url").Build(package);
DownloadPackage beforeStartPackage = download.Package;
await download.StartAsync();
```

**Comment by bezzad** [comment]
In the next version, I'll add a new argument to the `_downloader.DownloadFileTaskAsync(_pack);` method to set a new URL.
