### ISSUE TITLE
Question: Support for Old Versions

### ISSUE THREAD

**Issue by Taiizor** [bezzad/Downloader#168]
I'm curious why support for older .NET versions was removed.

In [my project](https://github.com/Taiizor/Sucrose), I target multiple .NET versions, so only supporting .NET 8 and above will no longer work for me. In order to keep third-party libraries up-to-date, if there won't be backward compatibility, I'll have to resort to alternative solutions.

**Comment by bezzad** [comment]
Hi @Taiizor, in the last version of the Downloader many codes changed according to performance and cross-platform issues such as using `IAsyncDisposable`, `CancelAsync`, `ValueTask`, etc.

Another reason is that the Downloader is being developed to use `HttpClient` and another new technology. When you want to work on MacOS or Linux distributions, I can't build it because of the lack of support for the .Net Framework.
I can also support `.Net 6.0` if you want, but it's not necessary to use that when .Net 8.0 exists.

Thanks to feedback

**Comment by Taiizor** [comment]
> Hi @Taiizor, in the last version of the Downloader many codes changed according to performance and cross-platform issues such as using `IAsyncDisposable`, `CancelAsync`, `ValueTask`, etc.
> 
> Another reason is that the Downloader is being developed to use `HttpClient` and another new technology. When you want to work on MacOS or Linux distributions, I can't build it because of the lack of support for the .Net Framework. I can also support `.Net 6.0` if you want, but it's not necessary to use that when .Net 8.0 exists.
> 
> Thanks to feedback

Wouldn't it be more appropriate to support .NET Standard 2.1 instead of .NET 6 or 8?

**Comment by Taiizor** [comment]
The [CancelAsync](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelasync?view=net-8.0#applies-to) method below is only valid for .NET 8 & 9. Therefore, it doesn't work with .NET 6 or .NET Standard 2.1.

https://github.com/bezzad/Downloader/blob/a50963c0f92aeabc8b8fa3a9c8652b446d5084e2/src/Downloader/ConcurrentStream.cs#L327

**Comment by bezzad** [comment]
Ok, no problem. if your problem is solved with `.NetStandard2.1` I will add it to the Downloader.

**Comment by bezzad** [comment]
New version v3.2.1 of the Downloader published on Nuget. please use it in your projects.
Thanks

**Comment by bezzad** [comment]
Thank you for your feedback!

While it's true that `.NET Standard 2.1` provides broad compatibility with many platforms, including .NET Core 3.0 and later, it does come with some **limitations** when compared to newer versions of .NET, like `.NET 8`.

### .NET Standard 2.1

- **Compatibility:** `.NET Standard 2.1` is indeed compatible with various platforms, including .NET Core, Mono, Xamarin, etc.
- **Limitations:** However, it **doesn't include all the latest features** introduced in .NET 5+ and beyond, particularly those in .NET 8 that are geared toward performance improvements and modern platform-specific features.

### .NET 8

- **Features:** By adding `.NET 8`, the library can leverage **newer features and performance optimizations** that aren't available in `.NET Standard 2.1`.
- **Compatibility:** Additionally, `.NET 8` is not backward-compatible with some older platforms, but it's ideal for **modern applications**.

Given that the goal is to support modern platforms and provide the best performance, I believe targeting both `.NET 8` and `.NET Standard 2.1` ensures the **widest compatibility** while allowing the use of the latest .NET features when needed.

Thanks again for raising this point, and I hope this clarifies the reasoning!
