### ISSUE TITLE
How is the thread safety of DownloadPackage guaranteed?

### ISSUE THREAD

**Issue by ktxiaok** [bezzad/Downloader#171]
I don't see any thread lock in DownloadPackage. It seems that it's only safe to access it in a callback of DownloadService.

**Comment by bezzad** [comment]
The `DownloadPackage` object primarily stores the index of download progress and is updated by a dedicated thread that writes incoming data from parallel download threads to disk. Only one thread handles updates to the Package, ensuring thread safety, as other threads download data concurrently and enqueue it for processing. This design avoids race conditions, and the Package can be serialized for resumption when the download is stopped. Changes to the Package only occur within a controlled, single-threaded context within the Downloader.

```csharp
// At first, keep and store the Package file to resume 
// your download from the last download position
DownloadPackage pack = downloader.Package;

// When you want to snapshot the current state of download, just need to serialize this object
pack.JsonSerialize(); // your method to serialization

// Resuming download after cancellation:
await downloader.DownloadFileTaskAsync(pack);
```

**Comment by ktxiaok** [comment]
Hi @bezzad , thanks for your reply! By the way, is it thread unsafe to modify DownloadConfiguration.MaximumBytesPerSecond directly on a external thread when the download is in progress? If it is, should I modify the DownloadConfiguration in a DownloadProgressChanged callback?

**Comment by bezzad** [comment]
@ktxiaok No any problem, you can change the download speed any time and anywhere that you want. To see how to do that, please go to [DownloaderIntegrationTest.cs => DynamicSpeedLimitTest() method](https://github.com/bezzad/Downloader/blob/8cc1101869593c899e33a47f4c8ecb04c4e7c5af/src/Downloader.Test/IntegrationTests/DownloadIntegrationTest.cs#L459) to test a complete sample.

**Comment by ktxiaok** [comment]
@bezzad Thanks!
