### ISSUE TITLE
GetFileSize may cause exception when HEAD method is not allowed

### ISSUE THREAD

**Issue by moonheart** [bezzad/Downloader#18]
Some url only allow `GET`, use `HEAD` may cause 403 exception.

https://github.com/bezzad/Downloader/blob/2940cc9be155ce60dc8435332e063ae09c880422/src/Downloader/DownloadService.cs#L143-L149

Maybe we could use `GET` to retrieve `Content-Length`?

**Comment by bezzad** [comment]
@moonheart Please give me a URL which I can test this problem. Thanks a lot.

**Comment by bezzad** [comment]
@moonheart I release the new version 1.9.0 and I fixed this issue. Please check that and tell me any existing problem.
Thanks a lot.

**Comment by moonheart** [comment]
@bezzad Sorry for late replying.

It's an url of my database backup so I cann't provide it, sorry for inconvinionce.

I've tested your latest 1.9.0 release, but unfortunenately it doesn't work. The problem is `GetResponseAsync` will throw directly if server returns with 403 forbbiden and the code didn't try-catch. Here is the exception message and stacktrace.

```
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Downloader.DownloadService.GetFileSize(Uri address) in D:\Git_Github\Downloader\src\Downloader\DownloadService.cs:line 146
   at Downloader.DownloadService.DownloadFileAsync(String address, String fileName) in D:\Git_Github\Downloader\src\Downloader\DownloadService.cs:line 70
```

I think we should use `GET` method directly instead of try `HEAD` method first since GetResponseAsync will not read the response body until we call `GetResponseStream`.

**Comment by bezzad** [comment]
I changed the GetFileSize method and for some reasons, I have to send the `HEAD` request first and change the type of request if a problem occurs. To start all requests as `GET`, I added an option which named `AllowedHeadRequest` to the lib that if you set that to a false value, all requests from the beginning will be the type of `GET`.
Please try new version 1.9.1 like below configs:

```csharp
var downloadOpt = new DownloadConfiguration();
downloadOpt.AllowedHeadRequest = true; // Can fetch file size by HEAD request or must be used GET method to support host
var ds = new DownloadService(downloadOpt);
await ds.DownloadFileAsync(url, fileName);
```

**Comment by moonheart** [comment]
Thanks for your working! It's now working without any problems.

**Comment by bezzad** [comment]
@moonheart I changed the GetFileSize method from version 2.0.0 onwards, and from now on all requests are GET method. Therefore, the option to AllowHeadRequests was also removed.

**Comment by moonheart** [comment]
@bezzad Thanks for your effort!
