### ISSUE TITLE
[Feature Request] Get Url File Name

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#23]
Please add this feature to get the file name and extension from the link Therefore, there is no need to specify the name and extension in the path

for example:

```
var downloader = new DownloadService(downloadOpt);
await downloader.DownloadFileAsync(url, "C:\myFolder")
```

**Comment by lindexi** [comment]
Yeah, I add this feature in my FileDownloader library: https://github.com/dotnet-campus/dotnetCampus.FileDownloader

**Comment by bezzad** [comment]
I trying to add this feature as soon as possible. Thanks for your feedback.

**Comment by bezzad** [comment]
Hi @ghost1372,
I added this feature to my library. Please check the new version 1.9.9.

**Comment by ghost1372** [comment]
Hi @bezzad thank you
just 2 tips:
1.It is not possible to identify the file name and extension in this kind of links:
`https://5743-zanjan.medu.ir/portal/fileLoader.php?code=0a1c53101df0e93134a7771606813229 `
solution:
```
byte[] data = client.DownloadData(downloadLink);
                    if (!string.IsNullOrEmpty(client.ResponseHeaders["Content-Disposition"]))
                    {
                        Name = client.ResponseHeaders["Content-Disposition"].Substring(client.ResponseHeaders["Content-Disposition"].IndexOf("filename=") + 9).Replace("\"", "");
                    }
```

2.Isn't it better to define the DirectoryInfo within the function itself?This will make it easier to use
`await ds.DownloadFileAsync(downloadItem.Url, downloadItem.FolderPath);
`

**Comment by bezzad** [comment]
I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks

**Comment by ghost1372** [comment]
> I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks

سلام اقای خسروی فر خسته نباشید ببخشید که به فارسی مینویسم
شما برای دریافت نام فایل از کد زیر استفاده کردید
`Path.GetFileName(uri.LocalPath);
`حالا چی میشه ما یه شرط بزاریم که چک کنه اخر لینک پسوند هست یا نه اگر بود کد بالا اجرا بشه و اگر نبود از هیدر نام فایل خونده بشه
نظرتون در این مورد چیه؟

**Comment by lindexi** [comment]
d

> 
> 
> > I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks
> 
> سلام اقای خسروی فر خسته نباشید ببخشید که به فارسی مینویسم
> شما برای دریافت نام فایل از کد زیر استفاده کردید
> `Path.GetFileName(uri.LocalPath); `حالا چی میشه ما یه شرط بزاریم که چک کنه اخر لینک پسوند هست یا نه اگر بود کد بالا اجرا بشه و اگر نبود از هیدر نام فایل خونده بشه
> نظرتون در این مورد چیه؟

@ghost1372  That's what I did, and I wrote Chinese blog: [Google Translate dotnet C# How to quickly get a url link to read the file name without the Internet ](https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fblog.lindexi.com%2Fpost%2Fdotnet-C-%E5%A6%82%E4%BD%95%E4%B8%8D%E8%81%94%E7%BD%91%E4%B8%8B%E5%BF%AB%E9%80%9F%E8%8E%B7%E5%8F%96%E4%B8%80%E6%AE%B5url%E9%93%BE%E6%8E%A5%E9%87%8C%E9%9D%A2%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6%E5%90%8D.html&sandbox=1 )

**Comment by bezzad** [comment]
> > I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks
> 
> سلام اقای خسروی فر خسته نباشید ببخشید که به فارسی مینویسم
> شما برای دریافت نام فایل از کد زیر استفاده کردید
> `Path.GetFileName(uri.LocalPath); `حالا چی میشه ما یه شرط بزاریم که چک کنه اخر لینک پسوند هست یا نه اگر بود کد بالا اجرا بشه و اگر نبود از هیدر نام فایل خونده بشه
> نظرتون در این مورد چیه؟

با سلام
سوال اینجاست که ما اکثر فایل هایی بدون پسوند هم برای دانلود داریم.
من برای حل مشکل فوق ابتدا هدر را بررسی میکنم و اگر نامی نداشت از روی url نام را میخوانم.
الان مشکلی که دارم در مورد encoding نام فایل در هدر هست که هرکاری میکنم به utf8‌ تبدیل نمیشود!
میتوانید در این زمینه خودتان بررسی کنید و اگر راهی پیدا کردید بهم کمک کنید؟

**Comment by ghost1372** [comment]
> > > I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks
> > 
> > 
> > سلام اقای خسروی فر خسته نباشید ببخشید که به فارسی مینویسم
> > شما برای دریافت نام فایل از کد زیر استفاده کردید
> > `Path.GetFileName(uri.LocalPath); `حالا چی میشه ما یه شرط بزاریم که چک کنه اخر لینک پسوند هست یا نه اگر بود کد بالا اجرا بشه و اگر نبود از هیدر نام فایل خونده بشه
> > نظرتون در این مورد چیه؟
> 
> با سلام
> سوال اینجاست که ما اکثر فایل هایی بدون پسوند هم برای دانلود داریم.
> من برای حل مشکل فوق ابتدا هدر را بررسی میکنم و اگر نامی نداشت از روی url نام را میخوانم.
> الان مشکلی که دارم در مورد encoding نام فایل در هدر هست که هرکاری میکنم به utf8‌ تبدیل نمیشود!
> میتوانید در این زمینه خودتان بررسی کنید و اگر راهی پیدا کردید بهم کمک کنید؟

بله خوشحال میشم اگر بتونم کمک کنم
نمونه لینک اگر دارید ضمیمه کنید تا من هم تست کنم

**Comment by ghost1372** [comment]
> d
> 
> > > I will try to implement this as well, but I do not promise that I can. Because there are a series of problems in implementing this type, first of all, how do we know if a link puts the name on the URL address or the header! There is a dichotomy, but I try to think more about that and I hope it is resolved. Thanks
> > 
> > 
> > سلام اقای خسروی فر خسته نباشید ببخشید که به فارسی مینویسم
> > شما برای دریافت نام فایل از کد زیر استفاده کردید
> > `Path.GetFileName(uri.LocalPath); `حالا چی میشه ما یه شرط بزاریم که چک کنه اخر لینک پسوند هست یا نه اگر بود کد بالا اجرا بشه و اگر نبود از هیدر نام فایل خونده بشه
> > نظرتون در این مورد چیه؟
> 
> @ghost1372 That's what I did, and I wrote Chinese blog: [Google Translate dotnet C# How to quickly get a url link to read the file name without the Internet ](https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fblog.lindexi.com%2Fpost%2Fdotnet-C-%E5%A6%82%E4%BD%95%E4%B8%8D%E8%81%94%E7%BD%91%E4%B8%8B%E5%BF%AB%E9%80%9F%E8%8E%B7%E5%8F%96%E4%B8%80%E6%AE%B5url%E9%93%BE%E6%8E%A5%E9%87%8C%E9%9D%A2%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6%E5%90%8D.html&sandbox=1)

thanks but your method not work for this url
`https://5743-zanjan.medu.ir/portal/fileLoader.php?code=0a1c53101df0e93134a7771606813229`
this link return a zip file

**Comment by bezzad** [comment]
@ghost1372 Yes, the code for this item has not yet been finalized to be pushed to the Github. Check this issue to yourself with the C# code and you will notice that the return value of a filename.rar is in incorrect encoding.

**Comment by bezzad** [comment]
@ghost1372, Please check the develop branch, let me know if there is a problem. Thanks

**Comment by ghost1372** [comment]
@bezzad  thank you worked very well 👏

but you should change your test

https://github.com/bezzad/Downloader/blob/b419fe25cf609eaed9b34571e1c161ae688d95be/src/Downloader.Test/RequestTest.cs#L40-L41

Because this link is only available from Iran IP and people who want to compile the project from outside Iran will not be a successful test.

**Comment by bezzad** [comment]
@ghost1372 yeah, I will change that.
