### ISSUE TITLE
System.IO.InvalidDataException: 'File size is invalid!'

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#26]
downloading file from github get error

`            await downloader.DownloadFileAsync("https://github.com/microsoft/winget-pkgs/archive/master.zip", "master.zip");
`

**Comment by ghost1372** [comment]
Also, sometimes the download is done but no file is created and i get exception in `Downloader_DownloadFileCompleted`


`System.IO.FileNotFoundException: 'Could not find file`

**Comment by bezzad** [comment]
@ghost1372 This is not a bug. Because this exception is thrown from `CheckSizes` method which checks to file total size.
I checked your URL and excited of. Sometimes the response of `GET` request, have `Content-Length` in that's Header and sometimes not have! 
According to issue #24, I will change my library to support downloading unknown length files.

**Comment by bezzad** [comment]
I checked this URL by Postman and that's the result is same and no content-length in the response Header.

**Comment by ghost1372** [comment]
thank you
Yes, sometimes the Header is empty
I am currently using webclient, file details are not available, but file can be downloaded
I hope the new version will be released soon
![Untitled](https://user-images.githubusercontent.com/9213496/103152265-a6ddf880-479b-11eb-992d-7c6397c528db.png)

**Comment by bezzad** [comment]
@ghost1372 Yes, in the new version I want to implement downloading without knowing `content-length`. But without length, you can't chunking file! So the parallel and multi chunk download feature is not available when server response has no `content-length`. And so downloads will just be one chunk and serial.

**Comment by ghost1372** [comment]
> @ghost1372 Yes, in the new version I want to implement downloading without knowing `content-length`. But without length, you can't chunking file! So the parallel and multi chunk download feature is not available when server response has no `content-length`. And so downloads will just be one chunk and serial.
It seems good, I do not think there will be a problem because in very rare cases this situation occurs
Inshallah When will it be published?

**Comment by bezzad** [comment]
I try this week to complete that. 😄

**Comment by bezzad** [comment]
@ghost1372 I added this feature to version 2.0.4. Please test and feedback on this issue. Thanks

**Comment by ghost1372** [comment]
thank you @bezzad Everything works fine❤
