### ISSUE TITLE
Cannot download to UNC path

### ISSUE THREAD

**Issue by rogerfar** [bezzad/Downloader#27]
When trying to download to a network UNC path like `\\server\d` it fails with the following exception:
`Drive name must be a root directory (i.e. 'C:\') or a drive letter ('C'). (Parameter 'driveName')`

This comes from this stacktrace:
```
System.ArgumentException: Drive name must be a root directory (i.e. 'C:\') or a drive letter ('C'). (Parameter 'driveName')
   at System.IO.DriveInfoInternal.NormalizeDriveName(String driveName)
   at System.IO.DriveInfo..ctor(String driveName)
   at Downloader.FileHelper.CheckDiskSize(String directory, Int64 actualSize)
   at Downloader.DownloadService.CheckSizes()
   at Downloader.DownloadService.Validate()
   at Downloader.DownloadService.StartDownload()
   at Downloader.DownloadService.DownloadFileAsync(String address, String fileName)
```

It's checking for the drive size here: https://github.com/bezzad/Downloader/blob/6a4e9d6ba3c70d119f6b695ab15c34b9225912a4/src/Downloader/FileHelper.cs#L39

Unfortunately drive info does not support UNC paths:
https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.-ctor?view=net-5.0
```
Use this class to obtain information on drives. The drive name must be either an uppercase or lowercase letter from 'a' to 'z'. You cannot use this method to obtain information on drive names that are null or use UNC (\\server\share) paths.
```

I think it might be best to simply skip doing the `CheckSizes` function when a network path is found?

**Comment by bezzad** [comment]
@rogerfar Thanks for submitting this issue. I try to solve this problem as soon as possible.

**Comment by rogerfar** [comment]
On a sidenote I just found too, I'm using the downloader in a Docker container and the same issues arises when trying to use a linux path like /data/.

**Comment by bezzad** [comment]
You are right. This will be fixed soon.

**Comment by bezzad** [comment]
Please test the new version `2.0.7` for this problem. Thanks

**Comment by bezzad** [comment]
@rogerfar Are your problem solved by the new version?

**Comment by rogerfar** [comment]
Sorry for the late reply, yes it seems to work!

**Comment by rogerfar** [comment]
@bezzad sorry to bring this up again but there is still a small issue, especially noticable when you are using this library in a Docker container.

My docker has a volume mapped to `/data/` to for example `C:\Temp` on my host machine.

When I run this C# commands in a docker container:
```
var spaceData = new DriveInfo("/data");
```
Then I get: `137656320000`. Which is correct, this is how space there is avaible on my C: drive.

But when I run:
```
var spaceData = new DriveInfo("/");
```
Then I get: `215317610496`. Which is not correct. This number is kinda a made up number by docker and can be different depending on your host system.

I noticed you are resolving the download path to root first, then checking if there is enough space, but I don't think you need to do that. Because if you do: `new DriveInfo(@"C:\Temp");`, it will give the same result as `new DriveInfo(@"C:\");`

**Comment by bezzad** [comment]
@rogerfar There is no problem if you open the issue several times. Thank you for stating this. However, your comments will evolve the app.
I modified this as follows and released a new version. I hope this version (2.1.1) fixes your problems.

```csharp
public static bool IsEnoughSpaceOnDisk(string directory, long actualSize)
{
    try
    {
        // var root = Path.GetPathRoot(directory); 
        var drive = new DriveInfo(directory);
        return drive.IsReady && actualSize < drive.AvailableFreeSpace;
    }
    catch (ArgumentException)
    {
        // null or use UNC (\\server\share) paths not supported.
        return true;
    }
}
```

**Comment by bezzad** [comment]
I added `CheckDiskSizeBeforeDownload` to `DownloadConfiguration` options for disabling check size of disk.
Check this feature in the new version 2.1.2 or later.
