### ISSUE TITLE
Not all chunks are downloaded in parallel

### ISSUE THREAD

**Issue by adreeeyan** [bezzad/Downloader#29]
On .Net Framework 4.8 projects, not all the chunks are downloaded in parallel.
The parallel downloads are only -1 of the total.

Here is the configuration with the output:
![image](https://user-images.githubusercontent.com/18593260/105464091-f72d7500-5ccb-11eb-92bb-7f142d2281dd.png)

I think this commit caused this issue: https://github.com/bezzad/Downloader/commit/4fcbc34b0c42e70e0fdea02f6f4411e3038a5518
When I changed the `DefaultConnectionLimit` back to `1000` then the issue doesn't occur.
![image](https://user-images.githubusercontent.com/18593260/105464020-debd5a80-5ccb-11eb-9190-4e6773ad0d70.png)

Note: This issue only occurs in .net framework though, when I converted the project to .net core 3.1 the issue didn't occur.

**Comment by bezzad** [comment]
@adreeeyan Please test the new version 2.0.7 for this problem. Thanks

**Comment by adreeeyan** [comment]
@bezzad  It's working now, thank you!
