### ISSUE TITLE
"File size is invalid!" when using DownloadFileAsync

### ISSUE THREAD

**Issue by goaaats** [bezzad/Downloader#3]
I'm trying to download a relatively big file, but it seems like your HEAD request to get the file size doesn't resolve correctly in this case.
It throws the exception here: https://github.com/bezzad/Downloader/blob/f11f10df6e3a566dbbc92d6a1ab31b6262705b87/src/Downloader/DownloadService.cs#L71

The URL I'm trying to get is http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001a.patch
When checking with insomnia, I do get a correct Content-Length back via HEAD.
![image](https://user-images.githubusercontent.com/16760685/84567078-8eb20900-ad76-11ea-98d6-d17ec864799e.png)

Any idea why this might be the case? Am I using it wrong?

**Comment by goaaats** [comment]
Seems to be caused by https://github.com/bezzad/Downloader/blob/master/src/Downloader/DownloadService.cs#L107, you might wanna make this configurable - it's breaking on Akamai CDNs

**Comment by bezzad** [comment]
Hi @goaaats, 
Thank you for reporting this issue. You are right, this section should be configurable and I will set the default value to None.
I hope to fix it in the new version (1.2).

**Comment by bezzad** [comment]
New version (1.2) released. Please test with that to sure solved this issue.

**Comment by goaaats** [comment]
Perfect, works great, thanks a lot :thumbsup:
