### ISSUE TITLE
Some addresses cannot be downloaded

### ISSUE THREAD

**Issue by lnstock** [bezzad/Downloader#32]
Some addresses cannot be downloaded, but they can be downloaded using WebClient or a browser
For example, the following address:
http://static.didatravel.com/Static/1/49ba0137-d338-4a11-9366-bde212090370/AvailHotelSummary_V0.csv?Expires=1612323160&OSSAccessKeyId=jr9mtwydMaatBmPp&Signature=W%2BQ83fZ6uplswkZFJ0xLUIiNhGQ%3D

**Comment by bezzad** [comment]
This link result is:
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired.</Message>
  <RequestId>601A675B1FE13F363480191C</RequestId>
  <HostId>static.didatravel.com</HostId>
  <Expires>2021-02-03T03:32:40.000Z</Expires>
  <ServerTime>2021-02-03T09:05:31.000Z</ServerTime>
</Error>
```
Are you sure your link is correct?

**Comment by lnstock** [comment]
http://static.didatravel.com/Static/1/49ba0137-d338-4a11-9366-bde212090370/AvailHotelSummary_V0.csv?Expires=1612347191&OSSAccessKeyId=jr9mtwydMaatBmPp&Signature=%2F16JTp3A2y2%2FG2So8fLF61TLDAA%3D

**Comment by bezzad** [comment]
@lnstock This link do not work for me

**Comment by bezzad** [comment]
I used the below link and download csv file:
`http://static.didatravel.com/Static/1/49ba0137-d338-4a11-9366-bde212090370/AvailHotelSummary_V0.csv`
I checked your protocol and fix this issue as soon.
Thanks for this issue report

**Comment by bezzad** [comment]
@lnstock Can you give me a link with long expiration time? The last link expired too!

**Comment by lnstock** [comment]
You can visit this address http://106.75.131.6/ to get the link

**Comment by bezzad** [comment]
@lnstock thanks a lot

**Comment by bezzad** [comment]
This problem occurs when configuring the content type of request. Because some servers only support certain types of content. I fixed this problem, please check the new version `2.0.8`.
