### ISSUE TITLE
Download to Memory Stream ?

### ISSUE THREAD

**Issue by guillaumejay** [bezzad/Downloader#33]
I want to check things on  the download files before writing them on disk, so I planned to download to a memory stream, do my stuff, and then save on disk

But I can't find a method to do it..

**Comment by bezzad** [comment]
Use the `OnTheFlyDownload = true` option to caching in-memory.

**Comment by guillaumejay** [comment]
But if I want to automatiacally unzip a file (and not saving to disk the zip file), for example, I have to wait for it to be fully downloaded, and so, written on disk, right ?

**Comment by bezzad** [comment]
Yes, you right. you want to get the file on memory stream and store that by another way.
I add this feature as soon.

**Comment by bezzad** [comment]
I added this feature to version `2.0.9`. You can use that like below code:
```csharp
Stream destinationStream = await downloader.DownloadFileAsync(url); // without file name
```

**Comment by guillaumejay** [comment]
Thanks, I'l going to use it. (but I have another issue to fix first)
