### ISSUE TITLE
Package.Chunks always ignored

### ISSUE THREAD

**Issue by augustocb23** [bezzad/Downloader#36]
Hi, I'm trying to continue a previous started download.

I saved the package to a custom JSON file and restore it to create a `DownloadPackage` object. It works fine, just... don't continue from paused state!
The download start with the last percentage, but keep going until finish with 100% + last_state. Eg, if I paused with 37% and restart the app, the download will finish with 137%.

Reading the code, I've found something...

```charp
public async Task<Stream> DownloadFileAsync(DownloadPackage package)
{
    Package = package;
    InitialDownloader(package.Address.OriginalString);
    return await StartDownload().ConfigureAwait(false);
}

private async Task<Stream> StartDownload()
{
	// ...
	Package.Chunks = _chunkHub.ChunkFile(Package.TotalFileSize, Package.Options.ChunkCount);
}
```

In the code above, the package is read and `StartDownload` is called, but the chunks are always override. I have restored it's content, but this values isn't read and the whole file is downloaded again.

**Comment by bezzad** [comment]
@augustocb23 Please test the new version `2.1.3` for this problem. Thanks

**Comment by augustocb23** [comment]
Great, it works! 😃
Thanks

**Comment by augustocb23** [comment]
Great, it works! 😃
Thanks
