### ISSUE TITLE
High memory usage when downloading big files

### ISSUE THREAD

**Issue by goaaats** [bezzad/Downloader#4]
This is more of a feature request, but I'll write it down here anyways:

It would be nice if the library would use the final output file together with shared write streams during the download instead of allocating a buffer for the whole file at all times.
This causes very high memory usage when downloading big files, especially when downloading multiple of them, since memory for the whole file is allocated at all times.

Thanks!

**Comment by bezzad** [comment]
Have you set the OnTheFlyDownload option to true? 
This option is designed to download on RAM, and if the value is false, the download is done on HDD.

**Comment by goaaats** [comment]
I have, in the current head, it uses the same amount of RAM - with it set to true and to false. I already debugged this as well, it does take the appropriate codepaths.

**Comment by bezzad** [comment]
That's right. I fix that as soon as possible and you correctly can set it to false to download and cache on disk mode in next time.

**Comment by bezzad** [comment]
New version (1.2) released. Please test with that to sure solved this issue or not.

**Comment by goaaats** [comment]
Same thing here, basically unaffected now memory-wise, thanks a lot!

**Comment by ShihabSoft** [comment]
Hi there,

OnTheFlyDownload = true this definition is not in the DownloadConfiguration class anymore.

I am also experience very high memory usage while download a humungous file. I've searched through all the issues but I don't find any other alternatives for this setting.
