### ISSUE TITLE
Access UI Elements from ProgressChanged and DownloadCompleted events

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#41]
We cannot directly access UI elements from **ProgressChanged** and **DownloadCompleted** events
If we do that
`textblock.Text = "Progress";
`We get the following exception

> The calling thread must be STA, because many UI

So I have to use the dispatcher to solve this problem

**Comment by bezzad** [comment]
All downloader processes use the ‍`ConfigureAwait (true)` option. Therefore, requests are executed on non UI threads, and it makes sense for you to use the dispatcher to access view elements.
