### ISSUE TITLE
استفاده از try-catch

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#42]
سلام 
چرا خطا ها در
try-catch 
گرفته نمیشن؟
الان من گاهی دچار خطاهای مختلفی میشم و هیچ جوره نمیتونم از 
try-catch
برای مدیریت خطا استفاده کنم
الان توی تصویر زیر برنامه دچار اکسپشن شده ولی بلوک 
try-catch
اجرا نمیشه

![Untitled](https://user-images.githubusercontent.com/9213496/111649642-cd02ba00-8819-11eb-8dfa-77db76dc72ef.png)

**Comment by bezzad** [comment]
خطای کنترل شده دانلود از طریق خود رخ داد DownloadCompleted اعلام میشود.
