### ISSUE TITLE
Downloads file over 100% when continuing downloading from package info

### ISSUE THREAD

**Issue by Morasiu** [bezzad/Downloader#44]
Version: 2.2.4

![image](https://user-images.githubusercontent.com/19236279/112216158-79c9a680-8c21-11eb-8425-f0ddcea8f7f3.png)

When my app is loading a saved package from the file (serialized in binary) and continuing downloading, the `Downloader` is downloading and reporting progress over 100% (and over `TotalBytes`)! (Check `BytesReceived` and `Percent`)

It only happens when `Downloader` is continuing from the package.

My config:
```
var config = new DownloadConfiguration {
		CheckDiskSizeBeforeDownload = true,
		OnTheFlyDownload = false,
	};
```

Suggestions:
* My config is using `OnTheFlyDownload`  as `false`. I think that when is was `true` I didn't have that issue.
* My code for saving and loading package info is [here](https://github.com/Morasiu/AnimeVideoDownloader/blob/master/AnimeVideoDownloader/DownloaderLibrary/Helpers/DownloadPackageExtensions.cs). Maybe there is something wrong?

**Comment by bezzad** [comment]
@Morasiu Please check the new version 2.2.5 for this issue. 
If you found any problem please re-open this issue. thanks for reporting.

**Comment by Morasiu** [comment]
Looks like it always starts downloading from the beginning now. Even, when using the package as an argument.

**Comment by bezzad** [comment]
The Temp files that hold the information to the chunks are probably deleted. Please change the `DownloadConfigration.TempDirectory` address or make sure the files in the temp path of the operating system are safe. If this information is deleted after saving the package, it is impossible to continue downloading. Unless you use OnTheFly mode where buffer chunk information is stored on RAM.

**Comment by bezzad** [comment]
If you have another problem again, please open the new issue. Thanks a lot
