### ISSUE TITLE
Resume downloading doesn't start from saved temp file

### ISSUE THREAD

**Issue by Morasiu** [bezzad/Downloader#46]
Resume downloading doesn't start from a saved temp file. Instead, it appends more data into it.

This is a temp file saved in my custom directory just to test things out.

![image](https://user-images.githubusercontent.com/19236279/112343986-f01ee500-8cc3-11eb-9db5-69a51e6e4476.png)

> `1-chunkInfo` file is `Package` class saved on the disk using `BinaryFormatter`

![image](https://user-images.githubusercontent.com/19236279/112344912-ddf17680-8cc4-11eb-8897-2fa8a2766c6f.png)

It has more bytes (762 290 176 bytes) that `ReceivedBytesSize` and even more `TotalBytesToReceive` 762 290 176

![image](https://user-images.githubusercontent.com/19236279/112344210-2b211880-8cc4-11eb-9ad7-f5b0f3f34662.png)

I am using this setting to download it

```
var config = new DownloadConfiguration {
    CheckDiskSizeBeforeDownload = true,
    OnTheFlyDownload = false,
    TempDirectory = Config.DownloadDirectory
};
```

It starts the download from the begging every time I pass the `Package` object to it. After downloading it saves all bytes in file like that:

![image](https://user-images.githubusercontent.com/19236279/112345946-ca92db00-8cc5-11eb-8a59-96385c12de38.png)

It is 1.5 GB instead of 640 MB!

Am I doing something incorretly or is it a bug?

**Comment by bezzad** [comment]
@Morasiu What are your .Net version and which operating system?

**Comment by Morasiu** [comment]
Win10 and .Net 5.0.103 (but project is on .Net Core 3.1)

**Comment by bezzad** [comment]
@Morasiu 
I created a WPF sample at the `develop` branch to check this issue. But in my systems, no problem with stop and resume from the package file. Please test it on your current system if it is possible.
For test first, pull the `develop` branch and build the `Downloader.WPF.Sample` project. Then add your URL and file path to start the download. After a few seconds, stop the download and save the package file in a path. This time, where you put the download URL address, enter the address of the package file and press the start key to resume the download.
Does it start downloading from the beginning of the file or from where it left off?

**Comment by Morasiu** [comment]
Oh... I've tried it and it starts from the begging 

(Don't worry about progress bar artefacts, it looks distorted because of my GIF compressing making software)

![ScreenToGif](https://user-images.githubusercontent.com/19236279/112628876-cedd0680-8e33-11eb-926b-cc046e3231e3.gif)

**Comment by bezzad** [comment]
I fixed some things, please pull the `develop` branch and try again this scenario if possible. I am very sorry that repeating this process will cause you trouble. thank you for your cooperation.

**Comment by Morasiu** [comment]
Now it's working correctly. Thanks. I love your library ❤️

**Comment by bezzad** [comment]
@Morasiu Thanks a lot. ❤️
I release a new version (2.2.6) of these changes as soon as possible.
