### ISSUE TITLE
Resuming download starts from the begging and appends data to temp file.

### ISSUE THREAD

**Issue by Morasiu** [bezzad/Downloader#49]
Hello :)

I've found a weird bug. 

When I resume my download it starts from the beginning but appends data to the temp file.

## Process

![image](https://user-images.githubusercontent.com/19236279/113010997-9dd53c80-9179-11eb-98df-5c4c10fe56a5.png)

![image](https://user-images.githubusercontent.com/19236279/113011093-b5acc080-9179-11eb-8a9d-57a5b2442c73.png)

As you can see here is a file with 41MB from 50 MB file downloaded.  This is saved when I closed my app. 

Not when I resume and download another 30 MB, as you can see package looks correct and the temp file is the same. But progress says that it's started from the beginning.

![image](https://user-images.githubusercontent.com/19236279/113011529-2bb12780-917a-11eb-819e-fd13aba90a45.png)

![image](https://user-images.githubusercontent.com/19236279/113012126-c578d480-917a-11eb-8990-145c884be223.png)

But the temp file is now 75 MB

![image](https://user-images.githubusercontent.com/19236279/113011815-759a0d80-917a-11eb-85c5-65801280a3e9.png)

And if I let him download all file it saves all bytes in temp file into the new so... downloaded file has now 125 MB!

![image](https://user-images.githubusercontent.com/19236279/113012777-5fd91800-917b-11eb-8e6e-ede069a562a7.png)

## Config

```csharp
var config = new DownloadConfiguration {
  CheckDiskSizeBeforeDownload = true,
  OnTheFlyDownload = false,
  TempDirectory = Config.DownloadDirectory
};
```

Tested file: `http://ipv4.download.thinkbroadband.com/50MB.zip` (ignore the name `1.mp4`, it is that 50MB.zip file)

Package serialized using `BinarryFormatter`

Version: 2.2.6

**Comment by bezzad** [comment]
Hi @Morasiu 
I can't download from your URL:
![Screenshot 2021-03-30 220342](https://user-images.githubusercontent.com/10928710/113031364-dc7fec80-91a3-11eb-800a-a8e11cab18a3.jpg)

Does this always happen? 
Do other files have this problem in downloading?

**Comment by Morasiu** [comment]
I have a problem with all my files resuming. That file was just an example to test it correctly. I think it happens in 100% of cases. 

I've installed IDM and tried downloading this file. It downloaded without any problems and I could easily stop and resume download a few times.

But...

That doesn't solve that problem with the library creating corrupted files with more MB than the original file.

**Comment by bezzad** [comment]
I tested your URL with a VPN and that's correct. I ran this scenario several times in my program and there was no problem and even unit tests on different servers were not a problem. I think this problem can only occur when the package file is not saved at the right time or changes after the temp files after saved. The only right time to save the package file is after the download is cancelled. Therefore, if the values stored in the files do not match the package values, the downloader will start downloading from the begging.
Now, make sure that the package is saved right after the download is cancelled, which is the best place to make sure the inside is the `DownloadFileCompleted` events.

**Comment by Morasiu** [comment]
So... I'm writing an application that can download large files over not so stable connections. Can I use that feature of the library to resume downloading after someone computer shutdown unexpectedly or after their lost connection to the internet (I guess then event `DownloadFileCompleted` with some errors is fired?

Also, I'm not sure if I understand correctly. Can I save the package at any moment or not? If not how can I be sure, when to save the package? I'm currently saving a package every 10s of download using the `DownloadProgress` event.

**Comment by Morasiu** [comment]
I think it's still a bug if `DonwloaderService` is appending data over total bytes in downloaded file.

**Comment by bezzad** [comment]
Yes, this is a bug in appending data to the same temp files after restarting the download. But if you store the Package file after the cancelled event this problem not occur.
Let me find a way to save the package file whenever you want and resume whenever you want. Because for this scenario, only this method can work. Give me some time to implement this feature.

**Comment by bezzad** [comment]
@Morasiu Please test the new version 2.2.7 for this problem. Thanks

**Comment by Morasiu** [comment]
Resuming now works correctly. Thanks ❤️
