### ISSUE TITLE
Why is `donwloadSerice.CancelAsync()` called `async`?

### ISSUE THREAD

**Issue by Morasiu** [bezzad/Downloader#52]
Why is `donwloadSerice.CancelAsync()` called `async`? It doesn't return the task.

Should it be called just `Cancel()`?

**Comment by bezzad** [comment]
This method cancels a pending **asynchronous operation**.
for more info look at this [reference](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.cancelasync?view=net-5.0)

**Comment by Morasiu** [comment]
Is it working correctly?

I can see that in the method `ReadStream(Stream stream, CancellationToken token)` [LINK TO SRC](https://github.com/bezzad/Downloader/blob/88f9759a5ccfe55b350452d8c06bc7319b58624e/src/Downloader/ChunkDownloader.cs#L87) given token is omitted and new token (with Timeout) is passed to `stream.ReadAsync()`

So I guess I won't cancel until one chunk is fully downloaded

**Comment by bezzad** [comment]
Yes, that's work correctly.
In the method `ReadStream(Stream stream, CancellationToken token)` the given token used to download any block and the `innerCts` token is a timeout for a block.
So when you cancel the download process, the main cancel token (CTS) is called and finally stops after downloading a block from a chunk. By default, the value of a block is 8,000 bytes. The default timeout download a block is 1 second. Of course, all these values can be changed from the downloader configuration.

**Comment by Morasiu** [comment]
Okay. It was intended. Thank you!
