### ISSUE TITLE
Dispose of Filestorage removes the files

### ISSUE THREAD

**Issue by kishannarayan** [bezzad/Downloader#53]
FileStorage's dispose implementation is removing the files. Should it be just Closing the stream instead? Currently i am trying to extend the JsonConverter which will internally use FileStorage. As this is disposable, i also implement IDisposable to call the Dispose method in it. This converter is then used in a using block when i am deserializing, which kinda removes the files even before download is resumed.

**Comment by bezzad** [comment]
I close this issue and if you have any questions about this, so feel free to reopen that.
