### ISSUE TITLE
How to Use Pac Proxy?

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#59]
Hi @bezzad 
I have a pac file proxy, how can i use this proxy with DownloadService?
i tried this code but not worked:
```
var downloadOpt = new DownloadConfiguration()
{
    RequestConfiguration =
    {
        Proxy = new WebProxy("www.myserver.com/proxy/can.pac", true)
    }
};
var downloader = new DownloadService(downloadOpt);
```

in windows, i can set this url as a proxy (in internet Options) and works fine

**Comment by bezzad** [comment]
Please try the below way in a new console application and see you can do it or not?

```csharp
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(Url);
request.AllowAutoRedirect = true;
WebProxy myProxy = new WebProxy("www.myserver.com/proxy/can.pac", true);
myProxy.Credentials = new NetworkCredential("user", "password");
request.Proxy = myProxy;
HttpWebResponse response = (HttpWebResponse)Request.GetResponse();
```

Thanks.

**Comment by ghost1372** [comment]
now i get this error

` System.Net.WebException: 'The remote server returned an error: (421) Misdirected Request.'`

this is my pac url
`http://raw.githubusercontent.com/ghost1372/HandySub/master/Proxy/can.pac`
if you set in internet options you can access youtube and other websites
![image](https://user-images.githubusercontent.com/9213496/130353427-2d46bfb7-c1e7-4d2a-a6f1-a1919444440a.png)

but I found that any program created with .NET Core suffers from these problems and errors. There are no problems with the .NET Framework

**Comment by bezzad** [comment]
This is a .NET issue and no related to the `Downloader` library. Because I try to use this proxy with HttpClient or HttpWebRequest in .Net Core and get some errors.
I tried the below options in Downloader or HttpClient or pure HttpWebRequest:

``` csharp
Proxy = new WebProxy() {
    Address = new Uri("https://raw.githubusercontent.com/ghost1372/HandySub/master/Proxy/can.pac"),
    UseDefaultCredentials = false,
    Credentials = System.Net.CredentialCache.DefaultNetworkCredentials,
    BypassProxyOnLocal = true
}
```
So the httpClient get an error: `System.NotSupportedException: Only the 'http' scheme is allowed for proxies.`
I search this error and seem this issue is from `.NET Core` and many browsers only support http proxies, https proxies are not yet widely supported.
Please see [Unable to connect to HTTPS endpoint through WebProxy](https://github.com/dotnet/core/issues/2043) issue of `.NET Core`.

**Comment by ghost1372** [comment]
> This is a .NET issue and no related to the `Downloader` library. Because I try to use this proxy with HttpClient or HttpWebRequest in .Net Core and get some errors.
> I tried the below options in Downloader or HttpClient or pure HttpWebRequest:
> 
> ```cs
> Proxy = new WebProxy() {
>     Address = new Uri("https://raw.githubusercontent.com/ghost1372/HandySub/master/Proxy/can.pac"),
>     UseDefaultCredentials = false,
>     Credentials = System.Net.CredentialCache.DefaultNetworkCredentials,
>     BypassProxyOnLocal = true
> }
> ```
> 
> So the httpClient get an error: `System.NotSupportedException: Only the 'http' scheme is allowed for proxies.`
> I search this error and seem this issue is from `.NET Core` and many browsers only support `http` proxies, `https` proxies are not yet widely supported.
> Please see [Unable to connect to HTTPS endpoint through WebProxy](https://github.com/dotnet/core/issues/2043) issue of `.NET Core`.
> 
> Note: your proxy address is not real `http` and redirected on `https` and if you set the `http` on the proxy address you get an error:
> `The remote server returned an error: (404) Not Found.`
> Please test your proxy address on `HttpClient` or `HttpWebRequest` and if that has no issue so the downloader must be working correctly.

Yes, unfortunately, the problem is with .NET Core, anyway, thank you.
