### ISSUE TITLE
How do you resume a download?

### ISSUE THREAD

**Issue by LagradOst** [bezzad/Downloader#6]
I really want to use this in my project, but I cant find any type of start range. Right now I use 								connection.SetRequestProperty("Range", "bytes=" + rFile.Length() + "-"); for my own download, just so I can pick up where I stopped, but I cant find it in DownloadConfiguration or RequestConfiguration. Also is this project supported on Android, and can handle android paths?

**Comment by bezzad** [comment]
Thank you for your choice.
When the library starts downloading, it fills in the `DownloadService.Package` property value, which you must pass to the `DownloadFileAsync` function when you want to resume download.
I document how to use stop and resume download as soon as possible. But you can't set `Range` manually, cuz that exists in `Package` object.

**Comment by bezzad** [comment]
For resume from last download, store `downloader.Package` object and execute like this: (For more detail see [StopResumeOnTheFlyDownloadTest](https://github.com/bezzad/Downloader/blob/master/src/Downloader.Test/DownloadTest.cs#L88) test method)
```csharp
var pack = downloader.Package;
download.CancelAsync(); // Stopping after some second from the start of downloading.
await downloader.DownloadFileAsync(pack); // Resume download from stopped point.
```

**Comment by LagradOst** [comment]
The problem is that the download process in my project in the most cases just aborts (similar to End Task in task manager) and I need to resume download after you open the process again. In some cases I get a small window to save progress, but that cant be more than some ms, so in my slower downloader I just go of file size as start range. I want to use it because it is like 4x faster than my downloader, and I have not found any area2 solution that dosent require the .exe.

**Comment by LagradOst** [comment]
Looking over the download code, I think I can reimplement it in my project. The code is quite clean.

**Comment by bezzad** [comment]
If you want, you can send me a simple sample of your project or your upload link so I can see your problem and maybe fix it.

**Comment by LagradOst** [comment]
this is the main function for downloading the file: https://github.com/LagradOst/CloudStream-2/blob/f7409408856d5e9b3e6678ab50b3834f64e54714/CloudStreamForms/CloudStreamForms.Android/MainActivity.cs#L546

be aware it is quite spagett

**Comment by bezzad** [comment]
@LagradOst  I released the new version v1.5.0. Please check this version. And if you have still this problem, please send me a sample project to check your problem. 
Thanks

**Comment by LagradOst** [comment]
idk man, my initial testing was of. Testing on Downloader.Sample Program.cs I got a minimum of 12s on 100mb (even tried to change config to the most optimal one, on 1gb it aprox the same speed on both, but it took way to long to link the chunks on your downloader so it was way slower).
```
var downloadItem = DownloadList[1]; 
s.Start();
var ds = await Download(downloadItem, downloadOpt);
Debug.WriteLine("ELAPSED: " + s.ElapsedMilliseconds);
await Task.Delay(1000); 
ds.Clear();
```
and 
```
var downloadOpt = new DownloadConfiguration {
                ParallelDownload = true, // download parts of file as parallel or not
                BufferBlockSize = 10240, // usually, hosts support max to 8000 bytes
                ChunkCount = 8, // file parts to download
                MaxTryAgainOnFailover = int.MaxValue, // the maximum number of times to fail.
                OnTheFlyDownload = false, // caching in-memory or not?
                Timeout = 1000, // timeout (millisecond) per stream block reader
                MaximumBytesPerSecond =int.MaxValue, // speed limited to 1MB/s
                RequestConfiguration = // config and customize request headers
                {
                    Accept = "*/*",
                    UserAgent = $"DownloaderSample/{Assembly.GetExecutingAssembly().GetName().Version.ToString(3)}",
                    ProtocolVersion = HttpVersion.Version11,
                    KeepAlive = false,
                    UseDefaultCredentials = false
                }
            };
```
while this took 4-9 sec
```
 Stopwatch s = new Stopwatch();
            s.Start(); 
             
            string url = "http://ipv4.download.thinkbroadband.com/100MB.zip";
            string path = "E:\\fast\\100mb.zip";

            HttpWebRequest webRequest = (HttpWebRequest)HttpWebRequest.Create(url);
            webRequest.ServerCertificateValidationCallback = delegate { return true; };
            webRequest.Method = "GET";
            webRequest.UserAgent = USERAGENT;
            byte[] data = new byte[1024];
            int count;
            FileStream output = new FileStream(path, FileMode.Append, FileAccess.Write);
             
            using (var webResponse = webRequest.GetResponse()) {
                try {
                    using (BinaryReader input = new BinaryReader(webResponse.GetResponseStream())) {
                        try {
                            long total = 0;
                            long filelen = 104857600; // 100mb

                            int cProgress()
                            {
                                return (int)(total * 100 / filelen);
                            }
                            int lastP = -1;
                            while ((count = input.Read(data)) != 0) {
                                output.Write(data, 0, count);
                                total += count;
                                int clen = cProgress();
                                if (lastP != clen) {
                                    lastP = clen;
                                    Debug.WriteLine(clen + "::" + s.ElapsedMilliseconds);
                                } 
                            } 
                        }
                        catch (Exception _ex) {
                            Debug.WriteLine("FATAL ERROR : " + _ex + "|" + url);
                        }

                    }
                }
                catch (Exception) {
                } 
            }
```

**Comment by bezzad** [comment]
Because the comparison conditions are not the same. For example, downloading your own multi-party has a primary and secondary overhead, which is a small size file increases the time. Or the amount of buffer. All of these must be the same. Second, the downloader itself uses the same HttpWebRequest, so the core is the same and only the way it is used is different. My suggestion is to do the test once again in ChunkCount = 1‌ and BufferBlockSize = 1024, because the same values ​​were in the top implementation.
