### ISSUE TITLE
Download information acquisition

### ISSUE THREAD

**Issue by LFMcxixif** [bezzad/Downloader#60]
How can I get the name of the Url download file

**Comment by ghost1372** [comment]
```
private static void OnDownloadFileCompleted(object sender, AsyncCompletedEventArgs e)
        {
            var file = e.UserState as DownloadPackage;
            //file.FileName
        }
```

**Comment by LFMcxixif** [comment]
> ```
> private static void OnDownloadFileCompleted(object sender, AsyncCompletedEventArgs e)
>         {
>             var file = e.UserState as DownloadPackage;
>             //file.FileName
>         }
> ```

For example, the Url is https://download.com/Download.exe, I want him to automatically name the file and save it to the directory /Download/Download.exe, what should I do?

**Comment by ghost1372** [comment]
> > ```
> > private static void OnDownloadFileCompleted(object sender, AsyncCompletedEventArgs e)
> >         {
> >             var file = e.UserState as DownloadPackage;
> >             //file.FileName
> >         }
> > ```
> 
> For example, the Url is https://download.com/Download.exe, I want him to automatically name the file and save it to the directory /Download/Download.exe, what should I do?

DirectoryInfo path = new DirectoryInfo("Your_Path");
string url = @"https://file-examples.com/fileName.zip";
await downloader.DownloadFileTaskAsync(url, path); // download into "Your_Path\fileName.zip"

**Comment by LFMcxixif** [comment]
> > > ```
> > > private static void OnDownloadFileCompleted(object sender, AsyncCompletedEventArgs e)
> > >         {
> > >             var file = e.UserState as DownloadPackage;
> > >             //file.FileName
> > >         }
> > > ```
> > 
> > 
> > 比如Url是https://download.com/Download.exe，我想让他自动给文件命名并保存到目录/Download/Download.exe，我该怎么办？
> 
> ```
> DirectoryInfo path = new DirectoryInfo("Your_Path");
> string url = @"https://file-examples.com/fileName.zip";
> await downloader.DownloadFileTaskAsync(url, path); // download into "Your_Path\fileName.zip"
> ```

No, I mean to get the download file name from the server instead of defining the file name in the program

**Comment by ghost1372** [comment]
You did not pay attention to what I said, This is what you want. You just specify the folder, the file name is get automatically

DirectoryInfo path = new DirectoryInfo("D:\Download");
string url = @"https://file-examples.com/fileName.zip";
await downloader.DownloadFileTaskAsync(url, path); // download into "Download\fileName.zip"

**Comment by LFMcxixif** [comment]
> 你没注意我说的，这就是你想要的。你只需要指定文件夹，文件名是自动获取的
> 
> ```
> DirectoryInfo path = new DirectoryInfo(@"D:\Download");
> string url = @"https://file-examples.com/fileName.zip";
> await downloader.DownloadFileTaskAsync(url, path); // download into "Download\fileName.zip"
> ```

But my link is different from yours, it is a straight link

Like this: https://pan.tpcraft.cn/api/v3/file/source/7/Java8%2064%E4%BD%8D.exe?sign=TuX1WLnbXtd0V7RmoFDvvmqgMN8EmVNs03xeacaNqGA%3D%3A0

**Comment by bezzad** [comment]
@LFMcxixif Are you test the below codes and that doesn't work for you?

```
DirectoryInfo path = new DirectoryInfo(@"D:\Download");
string url = @"https://pan.tpcraft.cn/api/v3/file/source/7/Java8%2064%E4%BD%8D.exe?sign=TuX1WLnbXtd0V7RmoFDvvmqgMN8EmVNs03xeacaNqGA%3D%3A0";
await downloader.DownloadFileTaskAsync(url, path); // download into "D:\Download\Java8 64位.exe"
```

**Comment by bezzad** [comment]
I close this question issue, but anyone feels free to reopen if any questions about this issue.
