### ISSUE TITLE
Download M3U8 link and save to local disk issue.

### ISSUE THREAD

**Issue by zydjohnHotmail** [bezzad/Downloader#61]
Hello:
I want to test for download M3U8 links and save to local disk.  
I created one C# Console Project, target .NET 5.0, and I added the nuget package:
PM> Install-Package Downloader -Version 2.2.9
The following is my C# code: (OS: Windows 10)

`using Downloader;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace DownloaderTest
{
    class Program
    {
        public const string M3U8_Link1 = 
            @"http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8";
        public const string Local_MP4_File = @"D:\TestDownload\1.mp4";

        static async Task Main()
        {
            try
            {
                var downloadOpt = GetDownloadConfiguration();
                var downloader = new DownloadService(downloadOpt);
                await downloader.DownloadFileTaskAsync(M3U8_Link1, Local_MP4_File);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e);
                Debugger.Break();
            }
            Console.WriteLine("END");
            Console.Read();
        }

        private static DownloadConfiguration GetDownloadConfiguration()
        {
            string version = Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "1";
            var cookies = new CookieContainer();
            cookies.Add(new Cookie("download-type", "test") { Domain = "domain.com" });
            return new DownloadConfiguration
            {
                BufferBlockSize = 10240, 
                ChunkCount = 8,
                MaximumBytesPerSecond = 1024 * 1024, 
                MaxTryAgainOnFailover = int.MaxValue, 
                OnTheFlyDownload = false, 
                ParallelDownload = true, 
                TempDirectory = "C:\\temp", 
                Timeout = 1000, 
                RequestConfiguration = {
                    Accept = "*/*",
                    CookieContainer = cookies,
                    Headers = new WebHeaderCollection(), 
                    KeepAlive = true,
                    ProtocolVersion = HttpVersion.Version11, 
                    UseDefaultCredentials = false,
                    UserAgent = $"DownloaderSample/{version}"
                }
            };
        }
`

After I run my code, I saw the downloaded file: "D:\TestDownload\1.mp4"
But its size was only 1KB.
And I used another M3U8 downloader software to download the same M3U8 link and save in local disk, I found its size was: 29.7MB, and played in VLC media player, it is a MP4 video of 118 seconds, nearly 2 minutes.
What is wrong with my code, or is there any other issue with the repo?
By the way, in my real world job, I have to download a lot of live M3U8 links and save to local disks, most of them are live sports events, lasting about 2 hours.  Can I use this repo for my job?
Thanks,

**Comment by KoalaBear84** [comment]
Just some advice/info from a follower.

Download did it's job correctly, as it downloaded the oceans_aes.m3u8 file, which is 1010 bytes, so ~1 kB.

m3u(8) is like a playlist / index, which could contain multiple files / formats / qualities. See the contents:
```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.6.7)
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=319060,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=304x128
oceans_aes-audio=65000-video=236000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=461100,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=384x160
oceans_aes-audio=65000-video=370000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=674160,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=544x224
oceans_aes-audio=65000-video=571000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=999580,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=736x304
oceans_aes-audio=65000-video=878000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1489300,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=960x400
oceans_aes-audio=65000-video=1340000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2233420,CODECS="mp4a.40.2,avc1.66.31",RESOLUTION=1264x528
oceans_aes-audio=65000-video=2042000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=68900,CODECS="mp4a.40.2"
oceans_aes-audio=65000.m3u8
```

So what you have to do is parse the m3u file contents after downloading, and download the file you want.

There are already parsers for this like: https://github.com/jefersonsv/m3uParser.NET

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your explanation.  For all the live HLS streams I have to deal with, there is only one format/quality.
I can give you some examples in a few hours today.
So I want to know if I can download this type of HLS streams with only one format/quality in live and save it to local disk.
I have tried to use ffmpeg to download HLS stream, it seems working, but I found it has some issue, the biggest issue is I can’t use ffmpeg to download HLS stream asynchronously, I have to wait for the download to finish, which is impossible in my program, I have many other similar downloads to run at the same time, I can’t wait for any single of the download to finish.
Pleas advise on if I can use this repo to download single format/quality HLS stream in live and save as a MP4 file to local disk.
Thanks,

**Comment by bezzad** [comment]
Hi @zydjohnHotmail,

An M3U8 file is a playlist file used by various audio and video playback programs. It contains a path or URL to a media file or folder of media files, along with information about the playlist. M3U8 files use the same formatting as . M3U files, except the text stored in the files uses UTF-8 character encoding.

So downloader library can't convert your `.M3U8` files to video or audio files. But you can download the playlist file and parse it with your own app to the multiple links. Then download asynchrony every part of a playlist with the downloader and play every part or merge all parts after downloading all with `ffmpeg.exe`.

**Comment by duci95** [comment]
> Just some advice/info from a follower.
> 
> _edit_ I see you have asked this on multiple repositories: [dotnettools/SharpGrabber#41](https://github.com/dotnettools/SharpGrabber/issues/41)
> 
> Download did it's job correctly, as it downloaded the oceans_aes.m3u8 file, which is 1010 bytes, so ~1 kB.
> 
> m3u(8) is like a playlist / index, which could contain multiple files / formats / qualities. See the contents:
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:1
> ## Created with Unified Streaming Platform(version=1.6.7)
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=319060,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=304x128
> oceans_aes-audio=65000-video=236000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=461100,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=384x160
> oceans_aes-audio=65000-video=370000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=674160,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=544x224
> oceans_aes-audio=65000-video=571000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=999580,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=736x304
> oceans_aes-audio=65000-video=878000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1489300,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=960x400
> oceans_aes-audio=65000-video=1340000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2233420,CODECS="mp4a.40.2,avc1.66.31",RESOLUTION=1264x528
> oceans_aes-audio=65000-video=2042000.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=68900,CODECS="mp4a.40.2"
> oceans_aes-audio=65000.m3u8
> ```
> 
> So what you have to do is parse the m3u file contents after downloading, and download the file/format/quality you want. And it looks you get another m3u8 first which will contain the actual files needed 😂
> 
> There are already parsers for this like: https://github.com/jefersonsv/m3uParser.NET
> 
> Or you might use ffmpeg to do the heavy work: https://gist.github.com/tzmartin/fb1f4a8e95ef5fb79596bd4719671b5d

What to do when I parse it using m3uParser, how to get video file?

**Comment by KoalaBear84** [comment]
I have no idea, never worked with it.
