### ISSUE TITLE
Allow setting a speed limit on downloads

### ISSUE THREAD

**Issue by goaaats** [bezzad/Downloader#7]
Please allow setting a speed limit for downloads in the DownloadConfiguration object.
It's an often requested feature for things like updaters that have to download big files, and would otherwise suck up all the bandwidth on the network.

If this is already possible and I haven't found the right way to do it, please let me know.

Thank you!

**Comment by bezzad** [comment]
@goaaats that's Good point. I think this is done by pausing and resuming the download, like `Throttled Streams`. 
But let me do more research on that to add something sure. I hope you see it in the next version. Thank you for your suggestion.

**Comment by bezzad** [comment]
I add `MaximumBytesPerSecond` property to config to set your bytes per the second limitation in your download config. You can test it in this new version 1.3.0.

**Comment by bezzad** [comment]
@goaaats have you tried this to make sure it works? Can I close this issue?

**Comment by goaaats** [comment]
Hey! I've had a chance to update and trial this, the speed limiting seems to work fine, however, since this version of the package, I seem to be running into major memory leaks with the downloader class after a while - I haven't had a chance to investigate further, but I can try checking with dotMemory tonight or tomorrow. I don't think any of my changes could have caused this.

Here's my code, if you want to have a look: https://www.github.com/goatcorp/FFXIVQuickLauncher/tree/master/XIVLauncher%2FGame%2FPatch%2FPatchManager.cs#L130

**Comment by bezzad** [comment]
Thank you for what you did. I will explore this issue of memory leak more deeply soon to be solved. If you find something that you think will help, sure tell me.
Thank you very much

**Comment by goaaats** [comment]
Hey, sorry about this! Turns out I had a bug in my UI implementation related to downloading that was causing this, so no problem with the library.

Sorry again, thanks for your work!
