### ISSUE TITLE
DownloadService returns 404 error.

### ISSUE THREAD

**Issue by Whatareyoulaughingat** [bezzad/Downloader#72]
I'm getting a 404 error when trying to download even a single file but when i copy-paste the url to my browser it downloads just fine.

An example url: https://edge.forgecdn.net/files/3533/204/TinySkeletons-v1.0.1-1.16.5-Forge.jar

Here's the code:

`
public class DownloadHandler : IEnableLogger
{
    public Dictionary<string, string> ImportedFiles { get; set; } = new();

    public async Task StartAsync(string manifestFile, string minecraftFolder)
    {
        await using FileStream deserializationStream = System.IO.File.OpenRead(manifestFile);
        Manifest manifest = await JsonSerializer.DeserializeAsync<Manifest>(deserializationStream);

        using ForgeClient forge = new();

        foreach (Data.File file in manifest.Files)
        {
            string downloadUrl = await forge.Files.RetrieveDownloadUrl(file.ProjectId, file.FileId);
            string fileName = downloadUrl[(1 + downloadUrl.LastIndexOf('/'))..];

            // Start downloading.
            string destination = fileName.EndsWith(".jar") ? Path.GetFullPath(fileName, Path.GetFullPath("mods", minecraftFolder))
                                                           : Path.GetFullPath(fileName, Path.GetFullPath("resourcepacks", minecraftFolder));

            this.Log().Info($"URL: {downloadUrl}\n" +
                            $"Filename: {fileName}\n" +
                            $"Destination: {destination}\n");

            DownloadService downloader = await DownloadFile(downloadUrl, fileName, destination).ConfigureAwait(false);
            downloader.Clear();
        }
    }

    private async Task<DownloadService> DownloadFile(string downloadUrl, string fileName, string destination)
    {
        DownloadService currentDownloader = new(new DownloadConfiguration
        {
            BufferBlockSize = 4096,
            ChunkCount = 8,
            MaxTryAgainOnFailover = 2,
            OnTheFlyDownload = false,
            ParallelDownload = true,
            TempDirectory = Paths.Temp,
            Timeout = 10000,
            RequestConfiguration =
            {
                Accept = "*/*",
                KeepAlive = true,
                ProtocolVersion = HttpVersion.Version11,
                UseDefaultCredentials = false,
                UserAgent = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)",
            }
        });

        currentDownloader.DownloadStarted += (sender, downloadArgs) => this.Log().Info($"Started downloading {downloadArgs.FileName}");
        currentDownloader.DownloadProgressChanged += (sender, progressArgs) => this.Log().Info($"{fileName} - {progressArgs.ProgressPercentage}%");
        currentDownloader.DownloadFileCompleted += (sender, completedArgs) => this.Log().Info($"Finished downloading {fileName}");

        await currentDownloader.DownloadFileTaskAsync(downloadUrl, destination).ConfigureAwait(false);
        return currentDownloader;
    }
}`

**Comment by bezzad** [comment]
The problem is that your file server does not support chunking mode. You can only download it in one part and you can not break it down into several pieces. To detect this, I try to implement an algorithm that downloads in one chunk if the server is not supported that.

**Comment by Whatareyoulaughingat** [comment]
Okay, so i set the ChunkCount in the DownloadConfiguration to 1 instead of 8?

**Comment by Whatareyoulaughingat** [comment]
What do i need to do in order to download it in one part?

**Comment by bezzad** [comment]
No, the problem is that when adding a Range on request. This causes the server not to be supported. We do not currently have code to ignore this condition and download without range. 
Give me a chance to fix it and I will let you know from here.

**Comment by bezzad** [comment]
I released a new version 2.3.4. Please get it and set the chunk count to 1 to ignore adding range to requests.
I hope your problem is solved. Thank you very much for the feedback that improved the library.

**Comment by Whatareyoulaughingat** [comment]
Everything works perfectly. Thanks for your help.
