### ISSUE TITLE
Using Downloader for FTP server

### ISSUE THREAD

**Issue by Soi9x** [bezzad/Downloader#73]
hi can anyone guide me to deploy Downloader for FTP server?

**Comment by bezzad** [comment]
@Soi9x Can you explain more exactly what you mean?

**Comment by Soi9x** [comment]
I have 1 IP address is 127.0.0.1 Port : 21 , Vitual patch is /Folder , I want to download using this downloader , download all files contained in /Folder , so how do I set up the code to have can use Downloader for FTP server

**Comment by bezzad** [comment]
No, The Downloader just could use the HTTP protocol.

**Comment by Soi9x** [comment]
Can you update more features to use for FTP?

**Comment by bezzad** [comment]
@Soi9x I think about that. Of course, everybody can join us and contribute to this project and so you can add FTP too.
Whatever, I thank you for your suggestion.
