### ISSUE TITLE
Detect token included in download link and add it to headers

### ISSUE THREAD

**Issue by david127cu** [bezzad/Downloader#74]

**Comment by bezzad** [comment]
@david127cu Can you explain more exactly what you mean?

**Comment by david127cu** [comment]
This is an example of a link that includes the token:

https://www.seedr.cc/download/archive/aff9f8702381e69c3a956a859db90e7be8bd20619a0480094d5bb8b9a288fd2c?token=bfcfe31f82448dda264153ec0e2170ce54fa1e4383c251b09853805a6d33a104&exp=1642355722

**Comment by bezzad** [comment]
First, you must explain whats is your mean about the token and why we should add it to the header?
Second, your link has a "403 Forbidden" error!
