### ISSUE TITLE
Download save file path problem

### ISSUE THREAD

**Issue by LFMcxixif** [bezzad/Downloader#75]
Does the file path saved after downloading have to use "\"? , can't I use "/"?

**Comment by bezzad** [comment]
@LFMcxixif Can you explain more exactly what you mean?
Give your `DownloadConfiguration` to check what is your problem.

**Comment by LFMcxixif** [comment]
> @LFMcxixif你能更准确地解释你的意思吗？ 给你`DownloadConfiguration`检查你的问题是什么。

oh, I have something to do for the past two days and have no information to read, sorry.

I would like to ask, is the path to save the downloaded file an absolute path or a relative path?
Which should I use for "/" and "\" in the path?

**Comment by bezzad** [comment]
The download path is absolute and dependent on the OS path system. 
For example in Windows, you must give the path like this: `C:\Temp\MyFolder\` 
But in Linux, you must give the path like this: `/user/downloads/folder/`

**Comment by LFMcxixif** [comment]
> The download path is absolute and dependent on the OS path system. For example in Windows, you must give the path like this: `C:\Temp\MyFolder\` But in Linux, you must give the path like this: `/user/downloads/folder/`

Then I know, I have one last question, how to download files synchronously? instead of asynchronous downloads.

**Comment by bezzad** [comment]
So easy. you can call `.Wait()` after asynchronous methods to do sync mode. like below codes:

```csharp
downloader.DownloadFileTaskAsync(url, path).Wait();
```

**Comment by LFMcxixif** [comment]
> So easy. you can call `.Wait()` after asynchronous methods to do sync mode. like below codes:
> 
> ```cs
> downloader.DownloadFileTaskAsync(url, path).Wait();
> ```

okay, thank you!
