### ISSUE TITLE
Downloader uses Disk C: when downloading files

### ISSUE THREAD

**Issue by milkywayfarer** [bezzad/Downloader#76]
I'm using your library with the following configuration:
```
var downloadOpt = new DownloadConfiguration()
  {
      MaxTryAgainOnFailover = int.MaxValue,
      OnTheFlyDownload = false,
      ChunkCount = chunks,
      ParallelDownload = true,
      TempDirectory = Path.GetDirectoryName(path)
  };
var client = new DownloadService(downloadOpt);
await client.DownloadFileTaskAsync(item.From.ToString(), path);
```

Even though I specify the TempDirectory for the downloading task, disk C: is still in use and gets cluttered. I'm downloading a 20GB file while having only 5GB free on disk C: and I wonder if that can cause any problems for me and any users.

**Comment by bezzad** [comment]
Are you sure the ‍`TempDirectory` path is not on your `C` drive? 
Please try the below option to sure this config is correct:

```
TempDirectory = "D:\Temp"
```

**Comment by milkywayfarer** [comment]
`path = Path.Combine(Variables.Directories["TempDirectory"], Thread.CurrentThread.ManagedThreadId.ToString(), item.ToShort, Path.GetFileName(item.To))`, where `Variables.Directories["TempDirectory"]` is `Path.Combine(Directory.GetCurrentDirectory(), "temp")`. I run my app from Z: drive. Debug shows that the `path` variable is correctly passed to the configuration.

**Comment by bezzad** [comment]
Is the ‍`Z:\` drive a network drive or not on your local hard drive?

**Comment by milkywayfarer** [comment]
It is a local SSD.

**Comment by bezzad** [comment]
Nowhere in the library do we give a path to the‍ `C:` drive or the operating system. Your `TempDirectory` path may not be correct at runtime, and you may set the value after creating the `DownloadService` object. Then sets the default download path, which is in the operating system drive. For example is your code like below:

```csharp
var downloader = new DownloadService(downloadOpt);
downloadOpt.TempDirectory = @"Z:\temp"; // this line no affect on downloader
```

If you have checked all the above and have no problem, please give me a little sample of your app or if your project is open source, tell me the address so I can check it myself.
Thanks
