### ISSUE TITLE
Changing download speed on the go

### ISSUE THREAD

**Issue by milkywayfarer** [bezzad/Downloader#77]
I'm using `SemaphoreSlim` to organize the download of multiple files at once. I want to change the download speed every time the `SemaphoreSlim` releases.

I set `var limiter = 10` before the download starts. It indicates that the maximum download speed across all threads in semaphore is 10 Mbit/sec and the `SemaphoreSlim` is allowed to run 10 threads at once too. At the end of download list, there is a moment where there are, for example, only 5 out of possible 10 threads are working, so I want to change their speed to be not 5Mbit/sec collectively, but 10.

**Comment by bezzad** [comment]
I will add this new feature to the library soon. Thanks for your feedback.

**Comment by bezzad** [comment]
Please test the latest version 2.3.2 to solve this problem.
