### ISSUE TITLE
Download speed not maximized

### ISSUE THREAD

**Issue by fengyuan213** [bezzad/Downloader#8]
The new feature/logic added seems to slow down the download speed even I set it to no limit. I tried to download the file with IDM and it reached 30MB/s(around 300mbps). I only have around 6MB/s(around 60Mbps) speed with version 1.2. In the version 1.1 the problem does not exist.
![image](https://user-images.githubusercontent.com/26819159/85914006-2e3dc400-b86c-11ea-8d20-d24959d7433c.png)

**Comment by bezzad** [comment]
Maybe you set the BufferSize in a small size! Increase the `BufferBlockSize` and check again, because this is directly related to downloading speed.

**Comment by bezzad** [comment]
@fengyuan213 Have you still this problem?
Can you give me your download config and test link?

**Comment by fengyuan213** [comment]
Download Url: http://resources.downloads.pokecity.club/2020.rar
Downloader configuration:

    var downloadOpt = new DownloadConfiguration
    {
        ParallelDownload = true, // download parts of file as parallel or not
        BufferBlockSize = 10240, // usually, hosts support max to 8000 bytes
        ChunkCount = 8, // file parts to download
        MaxTryAgainOnFailover = int.MaxValue, // the maximum number of times to fail.
        OnTheFlyDownload = false, // caching in-memory or not?
        Timeout = 1000, // timeout (millisecond) per stream block reader
        MaximumBytesPerSecond =0, //1024 * 1024, // speed limited to 1MB/s
        TempDirectory = "C:\\temp", // Set the temp path for buffering chunk files, the default path is Path.GetTempPath().
        RequestConfiguration = // config and customize request headers
        {
            Accept = "*/*",
            UserAgent = $"DownloaderSample/{Assembly.GetExecutingAssembly().GetName().Version.ToString(3)}",
            ProtocolVersion = HttpVersion.Version11,
            KeepAlive = false,
            UseDefaultCredentials = false
        }
    };

**Comment by darkoudeas** [comment]
Hi @bezzad 

Noticed exactly the same problem with similar config. When setting MaximumBytesPerSecond to zero , it actually slows down. Tried to debug it with no success.

Congrats for the awesome job and clean code :)

**Comment by darkoudeas** [comment]
Actually the problem is in BufferBlockSize when MaximumBytesPerSecond is set to zero. It gets value 1024 which delays download. Just set MaximumBytesPerSecond to max long

public void Validate()
        {
            var maxSpeedPerChunk = MaximumBytesPerSecond / ChunkCount;            
            ChunkCount = Math.Max(1, ChunkCount);
            MaximumBytesPerSecond = Math.Max(0, MaximumBytesPerSecond);
            BufferBlockSize = (int)Math.Min(Math.Max(maxSpeedPerChunk, MinimumBufferBlockSize), BufferBlockSize);
        }

**Comment by bezzad** [comment]
Hi @darkoudeas,
Thank you so much.
Please try my new release with version 2.0.1.
