### ISSUE TITLE
SSL connection Error

### ISSUE THREAD

**Issue by sami-soft** [bezzad/Downloader#80]
I get this error when I try to download a file in Windows 7, but I do not have this problem in other Windows.I installed Windows 7 inside VMware.

         The SSL connection could not be established

 
this is my code :

          download = DownloadBuilder.New()
                                 .WithUrl("https://bazresikar.mcls.gov.ir/fa/filepool/download/2d63d0adc6234345aae7704e5f3497ed")
                                .WithDirectory(fileDirectory)
                               .WithFileName("1.pdf")
                              .Build();

**Comment by bezzad** [comment]
This is the `HttpRequestException` and then you have an inner exception that explains what is the main issue. 
The above error message is displayed for most network problems and this is thrown from .NET base classes and has nothing to do with the downloader. So first look at the internal error and make sure you set the settings correctly.
