### ISSUE TITLE
JSON Serialization is not possible

### ISSUE THREAD

**Issue by michalpaukert** [bezzad/Downloader#81]
Since [FileStorage ](https://github.com/bezzad/Downloader/blob/master/src/Downloader/FileStorage.cs)and [MemoryStorage ](https://github.com/bezzad/Downloader/blob/master/src/Downloader/MemoryStorage.cs)classes are internal I am not able to use StorageConverter.

**Comment by bezzad** [comment]
I released version 2.3.3 which resolved this issue.
