### ISSUE TITLE
Set CheckDiskSizeBeforeDownload default value to false (not supported in Unity IL2CPP)

### ISSUE THREAD

**Issue by rubit0** [bezzad/Downloader#83]
I have been using this library in a Unity project and it works great but it does not work in Unity IL2CPP builds (specially iOS).
The issue is that System.IO.FileSystem.DriveInfo is not supported, setting CheckDiskSizeBeforeDownload to false fixes this.

I think it would be better to have that set by default to false.

**Comment by bezzad** [comment]
@rubit0 I did not find a simple solution to detect the lack of support for this command (`System.IO.FileSystem.DriveInfo`) and this is a problem in `.NET Core` itself on iOS Unity. It must now be turned off manually for iOS Unity. But please announce the .NET version you are using to perform the relevant test.
Thanks a lot.

**Comment by rubit0** [comment]
Unity converts the emitted .NET IL code to C++ code for improving performance (hence IL2CPP), so the .NET Runtime is not present at app runtime. If I find a workaround I will make PR.

**Comment by bezzad** [comment]
@rubit0 Thanks a lot.

**Comment by ecsplendid** [comment]
> present

Did you find a solution? I've got this issue now

**Comment by ecsplendid** [comment]
> The workaround for me was to set "CheckDiskSizeBeforeDownload" to false when building a new Downloadbuilder object.

Worked like a charm, THANK YOU sir! 🙏
