### ISSUE TITLE
Downloader.pdb not loaded

### ISSUE THREAD

**Issue by babakmdi** [bezzad/Downloader#86]
![image](https://user-images.githubusercontent.com/65450661/166675077-7e634103-1a36-4259-bc27-afbffd618c13.png)
Hello, 
when download is completed, i get this error! 
This is my code (WPF .NetCore 6): 

            var downloadOpt = new DownloadConfiguration()
            {
                ChunkCount = 8, 
                OnTheFlyDownload = true ,
                ParallelDownload = true  
            };
            var downloader = new DownloadService(downloadOpt);
            string file = @"C:\fileName.zip";
            string url = @"https://dl2.soft98.ir/soft/g/Google.Chrome.101.0.4951.54.x64.zip?1651664068";            
            downloader.DownloadProgressChanged += OnDownloadProgressChanged;          
            downloader.DownloadFileCompleted += OnDownloadFileCompleted;
            await downloader.DownloadFileTaskAsync(url, file);

        private void OnDownloadFileCompleted(object? sender, AsyncCompletedEventArgs e)
        {
            Console.WriteLine("Shod");
        }

        private void OnDownloadProgressChanged(object? sender, DownloadProgressChangedEventArgs e)
        {
            var a = e.ProgressPercentage * 100;
            Console.WriteLine(a);
        }

**Comment by bezzad** [comment]
I release a new version 2.3.5 and embedded the `PDB` file in the `Downloader.dll` file. 
Please get the new version of `Downloader` from Nuget or Github packages and check if this issue was solved or not.
Thanks a lot, @babakmdi.
