### ISSUE TITLE
Chunk Count

### ISSUE THREAD

**Issue by babakmdi** [bezzad/Downloader#88]
Can Chunk Count be increased after the download starts?

**Comment by bezzad** [comment]
@babakmdi No, you can't do this. Why do you need this feature?

**Comment by babakmdi** [comment]
multiple requests are not efficient for some servers.

**Comment by bezzad** [comment]
Ok no problem, Set chunk count equals 1.

**Comment by bezzad** [comment]
After download, you cant change this count because your chunks range was defined and if you change the chunks count get something wrong.

**Comment by babakmdi** [comment]
Before downloading, it is not clear whether the server supports it or not. For example IDM. Downloads first, then increases Number Chunk
