### ISSUE TITLE
Save Download Service In DataBase

### ISSUE THREAD

**Issue by babakmdi** [bezzad/Downloader#89]
Hi,
I want to save the download information in the database. How to save the Download Service in the database so that it can be used later?
I found a solution but it did not work properly, I converted DownloadService to json and after saving it in the database and then converting it to Download Service
No operation was performed and I received non public members Null.
Can you help me?

**Comment by babakmdi** [comment]
i dont know how should i restore download service.  i  serialize and deserialize my downloader package, now i dont know how should i give it to the download service, should i create new? 

this two examples are for exist download service = >
" {
Stop or Pause Download:
downloader.CancelAsync();
Resume Download:
await downloader.DownloadFileTaskAsync(pack); }   "

**Comment by bezzad** [comment]
Please check [this link](https://github.com/bezzad/Downloader/blob/31576ef12f592120195022d2459b9b440c841eba/src/Downloader.Test/UnitTests/DownloadPackageTest.cs#L34
) test method, it would be helpful to you.

If you can't solve your serialization issue, send me a little project which included your issue. Or share your project with me if it's the public repository.

**Comment by bezzad** [comment]
```
// create JSON setting
var settings = new Newtonsoft.Json.JsonSerializerSettings();
settings.Converters.Add(new StorageConverter());

// act
var serialized = Newtonsoft.Json.JsonConvert.SerializeObject(_package);
var deserialized = Newtonsoft.Json.JsonConvert.DeserializeObject<DownloadPackage>(serialized, settings);
```

**Comment by babakmdi** [comment]
after i serialized the package and save it into the database, and deserialized the json, how should i get it to the download service? can i do this ?

**Comment by bezzad** [comment]
```csharp
// deserialize your package
var pack = Newtonsoft.Json.JsonConvert.DeserializeObject<DownloadPackage>(serialized, settings);
// first create your downloader with your download options
var downloader = new DownloadService(downloadOpt);

// pass your deserialized package into the downloader and resume download
await downloader.DownloadFileTaskAsync(pack);
```
