### ISSUE TITLE
System.Net.WebException: 'An error occurred while sending the request. The response ended prematurely.'

### ISSUE THREAD

**Issue by fengyuan213** [bezzad/Downloader#9]
This error occur in version1.2's sample project. 
![image](https://user-images.githubusercontent.com/26819159/85914402-c8ebd200-b86f-11ea-9e64-e01bf5c48c39.png)
![image](https://user-images.githubusercontent.com/26819159/85914407-d1dca380-b86f-11ea-9637-69a3eb8ca752.png)
![image](https://user-images.githubusercontent.com/26819159/85914429-0a7c7d00-b870-11ea-80df-d54e1ff75788.png)
![image](https://user-images.githubusercontent.com/26819159/85914437-2122d400-b870-11ea-9323-8fe021b07220.png)

![image](https://user-images.githubusercontent.com/26819159/85914441-24b65b00-b870-11ea-9f7a-9f99f709809b.png)
StackTrace:
System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpConnectionPool.<SendWithNtConnectionAuthAsync>d__48.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__71.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
System.Net.HttpWebRequest.GetResponse()
![image](https://user-images.githubusercontent.com/26819159/85914449-41529300-b870-11ea-92ce-8ab2c748c930.png)

**Comment by bezzad** [comment]
Please give me your config. Some times the HTTP version or other options not supported from the server and you must change to stable config.

**Comment by fengyuan213** [comment]
![image](https://user-images.githubusercontent.com/26819159/85917601-1b3beb80-b88e-11ea-944c-581bdc296a07.png)
Actually this is just the clone version of master branch of your code...

**Comment by bezzad** [comment]
@fengyuan213  I released the new version v1.5.0 and must be fixed into that. Please check this version.

**Comment by bezzad** [comment]
@fengyuan213 Was this problem solved with the new version (v1.7.0)?

**Comment by fengyuan213** [comment]
System.IO.IOException
  HResult=0x80131620
  Message=The response ended prematurely, with at least 34256189 additional bytes expected.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Downloader.ThrottledStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\Fengyuan\Source\Repos\Downloader3\src\Downloader\ThrottledStream.cs:line 176
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

Problem not solved at all.. still the same 
Download Url: http://resources.downloads.pokecity.club/2020.rar
Downloader configuration:

            var downloadOpt = new DownloadConfiguration
            {
                ParallelDownload = true, // download parts of file as parallel or not
                BufferBlockSize = 10240, // usually, hosts support max to 8000 bytes
                ChunkCount = 8, // file parts to download
                MaxTryAgainOnFailover = int.MaxValue, // the maximum number of times to fail.
                OnTheFlyDownload = false, // caching in-memory or not?
                Timeout = 1000, // timeout (millisecond) per stream block reader
                MaximumBytesPerSecond =0, //1024 * 1024, // speed limited to 1MB/s
                TempDirectory = "C:\\temp", // Set the temp path for buffering chunk files, the default path is Path.GetTempPath().
                RequestConfiguration = // config and customize request headers
                {
                    Accept = "*/*",
                    UserAgent = $"DownloaderSample/{Assembly.GetExecutingAssembly().GetName().Version.ToString(3)}",
                    ProtocolVersion = HttpVersion.Version11,
                    KeepAlive = false,
                    UseDefaultCredentials = false
                }
            };
