### ISSUE TITLE
Download Failed 

### ISSUE THREAD

**Issue by ZCOREP** [bezzad/Downloader#91]
If the download was failed. How do i know? For example, the user's internet is disconnected.

**Comment by bezzad** [comment]
Download completed events that can include occurring errors or cancelled or download completed successfully.
`downloader.DownloadFileCompleted += OnDownloadFileCompleted;`

**Comment by ZCOREP** [comment]
Hello , I disconnected my wifi but "OnDownloadFileCompleted" is not working!

**Comment by bezzad** [comment]
I checked it and worked for me.
![image](https://user-images.githubusercontent.com/10928710/178783064-db78b6f0-1440-4970-9695-284f65d690ef.png)

Maybe you assigned `int.MaxValue` for `DownloadConfiguration.MaxTryAgainOnFailover`. So the Downloader tried again and failed again and repeated indefinitely.
Please check the `MaxTryAgainOnFailover` option and if it's less than 10 and also doesn't work, send me a part of your configuration or application to will be checked.

```csharp
var config =  new DownloadConfiguration {
                MaxTryAgainOnFailover = 1, // the maximum number of times to fail               
                Timeout = 500, // timeout (millisecond) per stream block reader, default values is 1000
}
```

**Comment by bezzad** [comment]
Could you had solve your problem? @ZCOREP

**Comment by ZCOREP** [comment]
Yes Thanks
