### ISSUE TITLE
File is downloaded from the beginning after resuming

### ISSUE THREAD

**Issue by tmk907** [bezzad/Downloader#94]
Sometimes, when you pause and resume the download, file is downloaded from the beginning.

This is my code:
```
Task.Run(() => downloader.DownloadFileTaskAsync(url, filePath)); //start
await Task.Delay(5000);
var package = downloader.Package;
downloader.CancelAsync(); //pause
using var stream = await downloader.DownloadFileTaskAsync(package); //resume
```
`StartDownload()` from 'resume' starts executing before `'start' StartDownload()` finishes.

When I resume download `downloader.DownloadFileTaskAsync(pack)` executes `InitialDownloader()`. New CancellationTokenSource is assigned to `_globalCancellationTokenSource` and  `IsCancelled` is false.
	
Then this code from `'start' StartDownload()` is executed and sets `Package.Chunks = null`
https://github.com/bezzad/Downloader/blob/42ce0a87fe8b99c5baf9ffae30d6336090266bd6/src/Downloader/DownloadService.cs#L162-L176
	
And when resume method continues to
[`	Package.Chunks ??= _chunkHub.ChunkFile(Package.TotalFileSize, Options.ChunkCount, Options.RangeLow);`](https://github.com/bezzad/Downloader/blob/42ce0a87fe8b99c5baf9ffae30d6336090266bd6/src/Downloader/DownloadService.cs#L139)
`Package.Chunks` are null which means that the download starts from the beginning.

Possible fix to this is use `SemaphoreSlim` in `StartDownload` method, so that resume will not start until first call finishes.

**Comment by bezzad** [comment]
Please check the new version 2.3.8. If the problem recurs, check the `Package.IsSupportDownloadInRange` option is false.
If this option is `False`, your URL server does not support downloads in specific ranges. Therefore, you cannot **stop** (cancel) and resume it from the last position. But you can **pause** and resume the download.
If the said option is `True` and the downloader starts from the beginning after restarting, give your URL and tell me to check.

**Comment by tmk907** [comment]
The problem still exists. I created sample app [https://github.com/tmk907/DownloaderIssue94](https://github.com/tmk907/DownloaderIssue94). `Package.IsSupportDownloadInRange` is `True`, so it's not problem with sample url. I noticed that if I add `await Task.Delay(1000);` after `downloader.CancelAsync();` resume works correctly.
It also works fine if I use 
```
    downloader.Pause();
    downloader.Resume();
```

**Comment by bezzad** [comment]
We need a safe cancellation and I can't cancel the reader task immediately after calling the cancel method. I just get the reader task aware about canceling with a token. Then it has to store critical progress information and close itself. But it takes time and when you call download again from the package immediately after canceling, it goes to error which we have no test to know. I want to add some tests and find out how to fix it.

**Comment by bezzad** [comment]
Please check the new version 2.3.9.

**Comment by tmk907** [comment]
2.3.9 works fine :ok_hand:
