### ISSUE TITLE
[Feature Request] Global MaximumBytesPerSecond limit

### ISSUE THREAD

**Issue by CodingOctocat** [bezzad/Downloader#96]
We may download multiple files at the same time and need to limit the global speed.

**Comment by bezzad** [comment]
The Downloader can download a file in multiple parts as parallel with global speed limitations. To control download speed you can use the `MaximumBytesPerSecond` property of Config.  

If you want to download multiple files from multiple URLs with a single Downloader like IDM, so you should add a Feature Request to the Download list of URLs. I'll try to add this feature as soon as possible.
