### ISSUE TITLE
Downloader corrupted some mp4 files

### ISSUE THREAD

**Issue by CodingOctocat** [bezzad/Downloader#98]
I am trying to download the Pixabay videos, but some of them only play for a short time and then the screen freezes. I tried to download the video using Chrome and everything works fine.

The code uses the simple example in README.MD

Test video:
[https://cdn.pixabay.com/vimeo/576083058/Hello%20-%2081605.mp4?width=1920&hash=e6f56273dcd2f28fd1a9fe6e77f66d7e157b33f6&download=1](https://cdn.pixabay.com/vimeo/576083058/Hello%20-%2081605.mp4?width=1920&hash=e6f56273dcd2f28fd1a9fe6e77f66d7e157b33f6&download=1)

Download via Downloader:
[1#-hello-Pixabay-81605-1920x1080.zip](https://github.com/bezzad/Downloader/files/9388502/1.-hello-Pixabay-81605-1920x1080.zip)

**Comment by bezzad** [comment]
Which version you are using?

**Comment by CodingOctocat** [comment]
v2.3.5

Also, I found the problem, when I set ChunkCount=1, the video plays normally

**Comment by bezzad** [comment]
Your download Server does not support downloading in multiple chunks. So you must download it in a single chunk.
But this is a big issue that the Downloader couldn't find out the server does not support chunking a file. I try to fix this problem in the next version.

![image](https://user-images.githubusercontent.com/10928710/185975194-55401c6a-9917-424e-9b5e-fee54189f652.png)

**Comment by bezzad** [comment]
The new version released and you can test it. If you have any issues with the new version, make sure to tell me.

**Comment by CodingOctocat** [comment]
v2.3.7 fixed this issue. :-)

**Comment by CodingOctocat** [comment]
Uh... I don't think the problem is completely solved, I tried to pause the download and resume, this issue and #99 appeared again.

My first test only paused once in the middle, the download progress, video content are normal, then I tested paused 3 times, not normal.

```CS
private void Cancel(object sender, RoutedEventArgs e)
{
    downloader.CancelAsync();

    pack = downloader.Package;
}

private async void Download(object sender, RoutedEventArgs e)
{
    var downloadOpt = new DownloadConfiguration() {
        ChunkCount = 8, // file parts to download, default value is 1
        OnTheFlyDownload = true, // caching in-memory or not? default values is true
        ParallelDownload = true // download parts of file as parallel or not. Default value is false
    };

    downloader = new DownloadService(downloadOpt);

    // Provide `FileName` and `TotalBytesToReceive` at the start of each downloads
    //downloader.DownloadStarted += OnDownloadStarted;

    // Provide any information about chunker downloads, like progress percentage per chunk, speed, total received bytes and received bytes array to live streaming.
    //downloader.ChunkDownloadProgressChanged += OnChunkDownloadProgressChanged;

    // Provide any information about download progress, like progress percentage of sum of chunks, total speed, average speed, total received bytes and received bytes array to live streaming.
    downloader.DownloadProgressChanged += OnDownloadProgressChanged;

    // Download completed event that can include occurred errors or cancelled or download completed successfully.
    //downloader.DownloadFileCompleted += OnDownloadFileCompleted;

    if (pack is not null)
    {
        await downloader.DownloadFileTaskAsync(pack);
    }
    else
    {
        await downloader.DownloadFileTaskAsync(@"https://cdn.pixabay.com/vimeo/576083058/Hello%20-%2081605.mp4?width=1920&hash=e6f56273dcd2f28fd1a9fe6e77f66d7e157b33f6&download=1", @"D:\Downloads\test.mp4");
    }
}

private void OnDownloadProgressChanged(object? sender, DownloadProgressChangedEventArgs e)
{
    DownloadInfo = $"{e.ProgressPercentage / 100:P2}";
}
```

**Comment by bezzad** [comment]
But I'll change the Download to know this download does not support download in range and when you stop and resume a download that continues from the beginning.

**Comment by CodingOctocat** [comment]
but i use Chrome browser and Thunder(a Chinese downloader, like idm) to download the video, they can pause/resume normally.

**Comment by bezzad** [comment]
I'll check if a browser can resume your download so it would be a way to do it. But your CDN does not support set Content-Range. I'll search does another way to get a special range without it because when we stop a download at an offset we need to tell the server to continue from that offset instead of beginning from zero.

**Comment by bezzad** [comment]
I checked the chrome browser and I realized it couldn't resume the download when you close your browser and continue again. Because your browser keeps the stream alive and when you click on resume it can continue downloading by existing stream. But when you close the browser and open it again the stream was disposed and it has to create a new stream which has to download from the beginning.

![image](https://user-images.githubusercontent.com/10928710/186381604-91269556-d0fd-415b-8981-9a5d94b10d40.png)

I found a solution to your problem. We can add a pause method to the Downloader which can suspend the download tasks without disposing of the stream and when you want to resume it can continue tasks. I guess it can be helpful to pause flow.

**Comment by CodingOctocat** [comment]
I think you are right. When I use Thunder to download, I pause the download and quit Thunder, then open it again to resume the download, Thunder works, but it uses a trick where I monitor its network activity and it secretly re-downloads in the background, creating the illusion that it can "resume".

**Comment by bezzad** [comment]
Please check the new version 2.3.8. 
If the problem recurs, check the `Package.IsSupportDownloadInRange` option is false.
If this option is `False`, your URL server does not support downloads in specific ranges. Therefore, you cannot **stop** (cancel) and resume it from the last position. But you can **pause** and resume the download.
If the said option is `True` and the downloader starts from the beginning after restarting, give your URL and tell me to check.

**Comment by CodingOctocat** [comment]
v2.3.8 work fine. thk:-)
